go-task/task

task.go

I wanted to run tools in sub directories of the directory Taskfile.yml lives in. For me it is more convenient to provide a directory to run the command(s) in then prefixing each command with `cd <path> && `

Added chdir to task

---

README.md
cmd/task/Taskfile.yml
task.go

Some tools need to have environment settings. This feature adds the ability to provide settings on a per task basis.

Allow specifying additional environment settings

---

task.go
testdata/generates/Taskfile.yml

Let's wait for #48 to be merged, then we can rebase this PR. This commit fixes #49.

Equal time (depends on #48)

---

README.md

Added "passing variables to dependencies"

Added "passing variables to dependencies"

---

completion/zsh/_task

Related to #103 
Put file like `docker/cli`
https://github.com/docker/cli/blob/master/contrib/completion/zsh/_docker

Add zsh completion

---

.travis.yml

Try out Windows builds in Travis

---

completion/ps/task.ps1

This PR adds a script to register a PowerShell completion helper
Relates to https://github.com/go-task/task/issues/103

Add PowerShell completion script

---

cmd/task/task.go

Switch to printing the version string to std out

---

completion/zsh/_task

Fixes: https://github.com/go-task/task/issues/346

Completion file honors includes

---

docs/taskfile_versions.md
docs/usage.md

Hello there,
I was reading through the documentation and found some possible typos.

Fix some typos in the documentation

---

completion/fish/task.fish

Completes available tasks:
Completes available flags:
Completes available options for flags:

Added fish completions

---

docs/usage.md

Fixes documentation confusion raised in #376.

Use {{default}} for an overriding usage

---

docs/installation.md

Fix little typo in installation doc.

Fix typo default installation

---

docs/installation.md

Updated the documented commands for installing Task using Go modules.

Update Go modules installation documentation for Go 1.16

---

status.go
task_test.go
testdata/status/Taskfile.yml

Hi, 
This PR fixes #411.
(This is my first PR for OSS! Sorry if I made a mistake:bow:)

Evaluate sources also if status is up-to-date

---

docs/community.md

Added a simple abstract about Sublime Text 4 package with the links to the source code and package control.

Update community.md about Sublime Text 4 package

---

task_test.go
testdata/ignore_nil_elements/cmds/Taskfile.yml
testdata/ignore_nil_elements/deps/Taskfile.yml
testdata/ignore_nil_elements/preconditions/Taskfile.yml
variables.go

This is to fix the issue #534 .
Only `cmds` attribute is pointed out in the issue, but I think other attributes such as `deps` and `preconditions` may have same problems, so I fix them as well.
Please let me know if there are any problems in fixed codes.

Fix segmentation fault on nil slice element for issue #534

---

go.mod
go.sum

upgrade mvdan.cc/sh/v3 v3.3.1 => v3.4.0

---

docs/usage.md

Fix typo in usage.md

---

task_test.go
taskfile/merge.go
testdata/ignore_nil_elements/includes/Taskfile.yml
testdata/ignore_nil_elements/includes/inc.yml

Fixes #612 
Also includes a fmt change for TestIncludesOptional.

Add nil check for included cmd

---

cmd/task/task.go

Consider a task:
```yml
test:
cmds:
- pytest {{.CLI_ARGS}}
```
Running `task test -- -m "not foo"` should be equivalent to running `pytest -m "not foo"`. However, with the current implementation the quoting of CLI_ARGS is lost and the task executes `python -m not foo`, which results in an error.

Fix quoting of CLI_ARGS

---

task.go

Add the verbose log entries for task started and task finished
Fixes #533

Adding task started and task finished in the verbose otput

---

.github/workflows/release.yml
.github/workflows/test.yml

Upgrade GitHub actions

---

init.go
internal/status/checksum.go
task_test.go

as of Go 1.16, ioutil is deprecated

replace usages of ioutil with io and os

---

.goreleaser.yml

This PR adds the completion files to the packages generated by nfpms, so they will be installed and managed automatically.

Add completions to nfpms packages

---

docs/installation.md

Add chocolatey in installation documentation

---

docs/README.md
docs/styleguide.md
docs/usage.md

Just a few small typos that I noticed as a newcomer to the docs. Cool project!

Docs: typo fixes

---

.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/test.yml
Taskfile.yml
help.go
internal/compiler/v2/compiler_v2.go
internal/sleepit/main.go
internal/templater/templater.go
task_test.go
taskfile/included_taskfile.go
taskfile/merge.go
taskfile/var.go
watch.go

Adding [staticcheck](https://staticcheck.io/) to prevent simple bugs on the code. Once merged, I'll make this CI step required for merging (done that for the tests themselves already).

Add golangci-lint

---

docs/docs/installation.md

Added Task to Fedora official repositories
I'm a Fedora  Linux packager and I have just added Task to the Fedora repositories.
I would appreciate you adding Fedora to the installation documentation.
Thanks,
-fuller

Add Fedora Linux to installation

---

errors.go
init.go
internal/execext/exec.go
internal/status/checksum.go
internal/templater/funcs.go
signals.go
task.go
task_test.go

Mostly `strings.ReplaceAll` and few octal numbers (ok, 1 misspelling 😉 ).
BTW, `task` is amazing, thank you!

Fix go-critic suggestions

---

CHANGELOG.md
docs/docs/api_reference.md
internal/compiler/v3/compiler_v3.go
setup.go
task_test.go
taskfile/read/taskfile.go
taskfile/task.go
testdata/special_vars/Taskfile.yml
testdata/special_vars/included/Taskfile.yml

Add ROOT_DIR and TASKFILE_DIR special variables

---

task_test.go
taskfile/read/taskfile.go
testdata/includes_incorrect/Taskfile.yml
testdata/includes_incorrect/incomplete.yml

resolves #885, although not exactly as proposed.

Add file path to YAML error message

---

.goreleaser.yml
docs/static/install.sh
install-task.sh

This pull request adds builds for armv5 and armv7 architectures.
Should also fix https://github.com/go-task/task/issues/842

fix: add armv5 & armv7 builds

---

task_test.go
taskfile/read/taskfile.go
testdata/includes_interpolation/Taskfile.yml
testdata/includes_interpolation/included/Taskfile.yml

Fixes #942 and adds a new test for it.

fix: interpolate includes taskfile and dir

---

docs/static/schema.json

fix: incorrect schema type for interval

---

docs/static/schema.json

fix: schema for output group

---

task.go

When the second execution of a Task needs to be skipped because it has already run (or is currently running), the code holds onto an execution slot while it waits for the first execution of the task to complete.
If the first execution of the task has already completed, this wait immediately completes, and the execution slot is also immediately freed.
If the first execution of the task is running its dependencies, it has temporarily released its execution slot to allow the dependencies to be run. Once those are complete, it attempts to reacquire an execution slot before running the commands for the task.
If there is only one execution slot, this gets blocked because the only slot is held by the second execution of the task.
Closes #715
Reproducing this deadlock wasn't too bad thanks to the …

Release execution slot while waiting for task

---

status.go
task_test.go
testdata/checksum/Taskfile.yml

>
>
Closes #840 
- **Disclaimer:** I'm not a `go` programmer. so if there is a more "idiomatic go" way of doing what i did, do tell.
- **Test:** As `TestStatusChecksum` checks exactly what I think should be checked in this case, I've added a `status` to the tested `Taskfile`. Without my changes to `status.go` this test will fail when running on the modified `Taskfile`

for task up to date check both status and sources

---

docs/docs/contributing.md

Fixes a couple of typos and update some links.

chore: minor fixes to contribution guide

---

docs/docs/community.md

Document mk tool support

---

docs/docs/api_reference.md

Optimize document structure so that navigation menu list matches content order.
Current:
New:
Preview: https://misitebao-taskfile-git-feature-update-documents-misitebao.vercel.app/api/

docs: optimize document structure

---

docs/docs/intro.md

Optimize the style of links in tables in documents so that Crowdin can parse them correctly.

docs: optimize document style

---

docs/docs/installation.md

When I was about to create the [winget-pkgs manifest](https://github.com/microsoft/winget-pkgs/tree/master/manifests/t/Task/Task) for the latest task release, I found that there was already a [PR](https://github.com/microsoft/winget-pkgs/pull/100783) pending review.

docs: add winget installation instructions

---

.github/workflows/upload-source-documents.yml

chore: fix auto upload workflow

---

cmd/task/task.go

Fix for swallowing unkown errors - fixes #1133

---

docs/docs/community.md
docs/docs/integrations.md

Preview: https://misitebao-taskfile-git-feature-improve-documentation-misitebao.vercel.app/

docs: fix broken links and paths

---

.github/workflows/website-deploy.yml
.github/workflows/website-test.yml

chore: add environment variables to the deployment environment

---

docs/docusaurus.config.js

Works:
Preview:
https://misitebao-fork-task-git-patch-1-misitebao.vercel.app/

style(website): improve language lable

---

.github/workflows/issue-awaiting-response.yml
.github/workflows/issue-closed.yml
.github/workflows/issue-needs-triage.yml

In accordance with the new scoped labels, a quick PR to update the workflows to use the new names

chore: update label names in workflows

---

docs/docusaurus.config.js

Works:
Preview:
https://misitebao-fork-task-git-feature-add-spanish-misitebao.vercel.app/

feat(website): add Spanish to the website

---

docs/docs/community.md

Add Conda community installation method

---

docs/docs/community.md

remove chinese translation repo from community.md

---

docs/docs/api_reference.md

chore: fix few typos in api_reference.md

---

CHANGELOG.md
docs/docs/usage.md
docs/static/schema.json
task.go
taskfile/task.go
variables.go

feat: add ability to set `watch: true` in Taskfile

---

precondition.go

Do not print precondition error if context was aborted

---

cmd/task/task.go
help.go

disables status check when running with --list --json options

feat: add --no-status option

---

cmd/task/task.go

feat: CLI_FORCE special variable

---

internal/compiler/v3/compiler_v3.go

Fixes #1435 
Looks like we made the error handling a little to aggressive in the last set of changes. The function that compiles the task/variables was erroring if a template value was not found even when we are asking it to FastCompile. During fast compilation, we should generally not care about templating errors as we are likely to be missing values.
The behaviour after this change is much closer to what happened pre-v3.33.0

fix: variable propagation

---

go.mod
go.sum
internal/orderedmap/orderedmap.go
internal/orderedmap/orderedmap_test.go

chore(deps): upgrade x/exp/slices

---

internal/experiments/experiments.go

Updates the way we look for an `.env` file. Currently, if you use the `--dir` or `--taskfile` flags when using `.env` to define which experiments are enabled, Task will look in the wrong directory since the default (`./env`) is relative to the user's current working directory, not the directory containing the Taskfile.

fix: experiment flags not working when .env is not in cwd

---

taskfile/reader.go

fix: remote prompt

---

internal/experiments/experiments.go

Do not use path package for operating system paths.

use path/filepath instead of path

---

task_test.go
taskfile/reader.go

Reported direct to me by @superdecimal
Fixes a regression of #1342 in 3.37.0+ after the DAG refactor

fix: nil schema panic

---

website/docs/usage.mdx
website/versioned_docs/version-latest/usage.mdx

This just fixes some broken links

docs: fix special variables link

---

task_test.go
taskfile/ast/for.go
testdata/for/cmds/Taskfile.yml
testdata/for/deps/Taskfile.yml
variables.go
website/docs/usage.mdx
website/static/schema.json

Closes #1766 
This seemed like low-hanging fruit. Very simple implementation. For now it will only accept raw values (no templating or reference resolving or anything like that). This should serve as a good first pass and we can build on it in the future if needed.

feat: loop over a matrix

---

completion/zsh/_task
website/docs/installation.mdx

Fixes #1796
If fixes for powershell but also for zsh
Based on #1807 , and github cli (`echo "$(gh completion -s zsh)"`)
I removed local that were not used.
I  also checked for fish and bash, it works well.

fix(completions): zsh and powershell completions

---

internal/flags/flags.go

docs(flags.go): flag description typo

---

website/versioned_docs/version-latest/faq.mdx

Update faq.mdx - fix typo

---

website/docs/usage.mdx

fix typo in [website/docs/usage.mdx](https://github.com/go-task/task/pull/1985/files#diff-0ae19208fa2e858250c5e65d8396bf745e4b3eb7413d342982b46317609f1a46)

fix typo in usage.mdx

---

internal/sort/sorter.go
internal/templater/funcs.go
variables.go

`gopls` has [a new `modernize` analyser](https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize) built into it. The changes in this PR are the result of applying:
`go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix ./...`
Only a couple of minor changes which is nice!

refactor: run task through modernize tool

---

website/docs/usage.mdx

The 'you' word has no sense here.

doc: fix: remove a word

---

internal/flags/flags.go
internal/sort/sorter.go
internal/sort/sorter_test.go

feat: create NoSort sorter for CLI sort option "none"

---

website/docs/experiments/experiments.mdx
website/versioned_docs/version-latest/experiments/experiments.mdx

docs: use .taskrc instead of .task-experiments.yml in our docs

---

task.go
task_test.go
testdata/deferred/Taskfile.yml

fix: interpolate vars in defer

---

website/.vitepress/config.ts

I've updated the crawler directly in Algolia, re-crawl it and tested it locally

docs: use Algolia as search engine

---

website/src/public/schema-taskrc.json

Added all experiments to the schema, clarifying which keys and values are expected. The schema will be updated during releases, allowing new experiments to be released without modifying the current schema

feat: add experiments to taskrc.yml schema

---

internal/flags/flags.go

fix: cache expiry in Taskrc was not working
