- README.md
- task.go
A very simple detection for cyclic dependencies like this:
```
build:
deps:
- build2
cmds:
- echo a
build2:
deps: 
- build
cmds:
- echo b
```
> Simple cyclic dependency detection

- task.go
Otherwise you have trailing white space in your vars.
> fix trailing white space for set instruction

- README.md
- task.go
If no argument is given try default. @andreynering Just a proposal
> Support for a default task

- cmd/task/task.go
- task.go
Enables printing of the run command, even when "set" is specified. I don't know if this is what we want, but it felt more consistent. I would have raised an issue first, but since the change was so small, I thought I would skip directly to the PR instead.
This PR also updates the help text to follow standard conventions. I renamed "target" in the help text to "task", since "target" often refers to the "target output file name".
Feel free to reject or request changes.
> Print on set

- cmd/task/task.go
- task.go
- task_test.go
- testdata/params/Taskfile.yml
Fixes issue #38 by allowing for template evaluation when calling a task with override variables:
```yaml
echo:
cmds:
- "echo {{.MYVAR}}"
default:
vars:
PLEASE: "awesome"
cmds:
- task: echo
vars: {MYVAR: "{{.PLEASE}}"}
```
> Allow template evaluation when calling a task with vars

- errors.go
- variable_handling.go
If you have errors in Taskvars.yml file it can get difficult to debug.
Without this pull request you got the error:
```bash
$ task build-web
exit status 127
```
With this pull request:
```bash
$ task build-web
task: Command "gite show -s --pretty=format:%cI" in taskvars file failed: exit status 127
```
> better error output for dynamic variables in Taskvars.yml

- task.go
- task_test.go
- testdata/params/Taskfile.yml
Fixes issue #42 by allowing for template evaluatation on task override
variables when the task is launched as dependency.
> Bugfix: allow templating when calling deps

- task.go
- task_test.go
- testdata/params/Taskfile.yml
- testdata/params/Taskvars.yml
- testdata/vars/Taskfile.yml
- testdata/vars/Taskvars.yml
- variables.go
UPDATE: This PR now ensures:
- Template evaluation finds placed _before_ copying the task for execution
- Template evaluation finds place _before_ dynamic variables are resolved
- Variable _priority order_ is in line with the documentation (also for default/named task)
- Template evaluation gets access to the following variables:
- Taskvars.yml: uncompiled static Taskvars.yml overwritten by environment variables.
- Task variables: resolved Taskvars.yml overwritten by uncompiled static task variables, environment variables and fully _resolved_ call parameters.
- Everything _inside_ a task: fully resolved variables for the task.
PS! This is now possible:
```yaml
task:
vars:
A: "no templating or sh:"
B: "{{.A}}"
```
These changes should finally resolve issue #40, and ensure it keeps working.
> Resolve issues with template- and dynamic variable resolution order and improve testing

- watch.go
Tasks are now called in a goroutine meaning the order of completion is *not* guaranteed. 
I'm not sure if task order is a requirement.
The reason they have to be called in a `goroutine` is because long running tasks would block `watchTasks(..)`, such that it doesn't read-in file change events.
The `goroutines` don't leak because the `context.CancelFunc` cancels the currently executing Task, causing `Executor.RunTask(..)` to return, thus exiting the `goroutine`.
I tested it locally and it appears to work correctly: long running processes are cancelled and re-started when a file change event occurs.
Resolves #60
> Cancel and restart long running process on file change by using context.WithCancel(..)

- README.md
- task.go
- task_test.go
- testdata/vars/multiline/Taskfile.yml
- variables.go
Fixes #63.
~Instead of giving an error on multiline results from sh, the results are now concatenated to one line by default, separated by a single space. Trailing and leading white space are stripped like before.~
~In adition, some flags have been added for advanced use cases to turn off line concationaton and/or trimming off leading/trailing white-space.~
Multiline results are now allowed, while the last newline is stripped to allow the output of most commands to work better as variable values. Some helper functions are added to make it easier to deal with multi-line variables in various ways.
> Added suport for multiline variables from sh

- docs/README.md
The links to installation doc were broken, perhaps it was a typo or maybe installation document was relocated from "installation" directory to "installation.md". In either case, making this change fixes the problem.
> Fix broken URL to installation doc

- internal/taskfile/read/taskfile.go
Hi! I've just added defined error instead `fmt.Errorf` where no arguments on string. Please review my change
> taskfile: return defined error when taskfile.yml is not found

- cmd/task/task.go
- task.go
Add command line option.
``` sh
$ task --help
..
Options:
..
-o, --output string   sets output style: [interleaved|group|prefixed]
..
```
Taskfile.yml
``` yaml
version: '2'
tasks:
test:
cmds:
- echo 'test'
```
Execute
``` sh
$ task -s test
test
$ task -s -o prefixed test
[test] test
```
> Add execute output style options

- completion/zsh/_task
When the taskfile has sub-tasks (eg: `task foo:bar`), the completion does not work correctly. That PR fixes that.
> Fix the zsh completion with sub-tasks

- internal/output/prefixed.go
This commit rewrites if-else chain as a switch.
Based on Go style guide:
https://golang.org/doc/effective_go.html#switch
> Rewrite if-else chain to switch statement

- internal/output/group.go
- internal/output/interleaved.go
- internal/output/output.go
- internal/output/output_test.go
- internal/output/prefixed.go
- task.go
This seems to fix some of the bugs reported by issues like #114 and #190.
Seems that the standard library's os/exec package has some black magic to detect if a writer is an actual *os.File, and some stuff are handled differently, then.
Fixes #114
Fixes #190
> Fixes some bugs relatated to commands output handling

- internal/taskfile/task.go
- task.go
- task_test.go
- testdata/dir/Taskfile.yml
- testdata/dir/explicit_doesnt_exist/Taskfile.yml
- testdata/dir/explicit_exists/Taskfile.yml
Also:
* Task directory: test when "dir:" attribute points to an existing dir
* Task directory: test default case (no "dir:" attribute)
* FIx spelling
Closes #209
> #209 When "dir:" attribute points to a non-existing dir, create it

- docs/usage.md
There is a dash missing in front of an echo command. This pull request fixes it.
> Add missing "-" in usage.md

- .gitignore
- docs/taskfile_versions.md
- docs/usage.md
- internal/taskfile/precondition.go
- internal/taskfile/precondition_test.go
- internal/taskfile/task.go
- internal/taskfile/version/version.go
- precondition.go
- status.go
- task.go
- task_test.go
- testdata/precondition/Taskfile.yml
- variables.go
This adds a `preconditions` stanza to the `task` stanza.  A precondition is _basically_ the inverse of a `status` in that it's a condition that _must_ succeed before the task can run.
Preconditions on file statuses doesn't make much sense, so preconditions are limited to `sh` interpreter invocations.  Furthermore - preconditions often require the user to do something in order to proceed, so they have a `msg` field that can be used to report next steps to the user.
I've added an "ignore_error" feature to preconditions, which will ignore errors in preconditions if the task is being executed as either a dependency or as a sub-task.  I'm not 100% this isn't a misfeature, but it was requested by our team, so it's there.   Normally a failure in a precondition will fail the task that it's on, …
> Add Preconditions to Tasks

- docs/usage.md
Forgot to document that now we create the directory if it doesn't exist.
> Document dir: creation (see PR #211)

- internal/status/checksum.go
- internal/status/glob.go
- internal/status/timestamp.go
- status.go
When using `method: checksum`, I was surprised to find out that even when files specified by `generates` do not exist the task won't get triggered as long as the source files are not modified. IMHO this behavior is unintuitive, especially considering how Makefile works. This PR adds a logic to re-run the task when files specified in generates do not exist.
> Re-run the task if generated files do not exist

- docs/usage.md
- go.sum
- internal/status/checksum.go
- internal/status/none.go
- internal/status/status.go
- internal/status/timestamp.go
- internal/taskfile/var.go
- internal/templater/templater.go
- task.go
- task_test.go
- testdata/checksum/Taskfile.yml
- variables.go
This introduces two special variables `{{.CHECKSUM}}` and `{{.TIMESTAMP}}` to `status` commands, to enable the checking of "up-to-dateness" of remote artifacts.
Generally, when you use `sources` - you also use `generates` - if the `generates` artifacts is newer than the `sources`, then the your task is out of date and needs to be re-run.  This works as long as you have direct access to the generated artifacts - but some tasks produce "remote artifacts" that don't live on the same file system as your sources (AMIs, Docker Images, Kubernetes Deploys) - `status` already supports `sh` based status checks - so we expanded this to evaluate remote artifacts.
Which ever method you choose to fingerprint your sources will be exposed as a template variable to `status` shell commands.
Currently, the …
> Expose timestamp and checksum to status

- completion/bash/task.bash
- completion/task.bash
Adds the bash autocomplete script into the repo (#103)
How to test it in Mac OS:
First make sure `bash-completion` is installed in your machine:
```shell
$ brew install bash-completion
```
It'll create `/usr/local/etc/bash_completion.d/` folder and add autocomplete files for your existing CLI tools.
For it to work, add this to your `~/.bashrc`:
```shell
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion
```
Now we're ready to add `task` autocomplete script:
Copy the bash autocomplete script and put it to `/usr/local/etc/bash_completion.d/task`. Start a new shell and it should work!
It's open to the feedback. I think we should add more documentation about autocompletion setup, as some users may not even know it exists for task.
> Bash autocompletion for task

- cmd/task/task.go
- task.go
I have a Taskfile with many different targets and the targets I want to run vary often enough I cannot just put them under another task's `dep`. I'm looking for when I run I supply the list of targets via the command line they will execute in parallel rather than sequentially.
Example of what I looking to
```
$ time task -p sleep1 sleep2
sleep 10
sleep 10
echo sleep 1
echo sleep 2
sleep 1
sleep 2
real	0m10.986s
user	0m0.755s
sys	0m0.530s
```
```yaml
version: '2'
tasks:
default:
deps:
- task: sleep1
- task: sleep2
- task: sleep3
sleep1:
cmds:
- sleep 10
- echo sleep 1
sleep2:
cmds:
- sleep 10
- echo sleep 2
sleep3:
cmds:
- sleep 10
- echo sleep 3
```
> Add flag to allow tasks provided on the command line to be run in parallel

- help.go
- internal/summary/summary.go
- task.go
- variables.go
Updates the `help.go` file to compile a task before printing its description. This enables templatization for the `-l` flag.
Also updates `summary/summary.go` and `task.go` to compile tasks before printing a summary.
Relates to https://github.com/go-task/task/issues/276
> Compile tasks before printing help or summary

- docs/installation.md
Hi, I've recently started maintaining Task for Arch Linux users here:
https://aur.archlinux.org/packages/taskfile-git
Any Arch Linux user can install it through their favorite package manager and
get the latest version of package. Unfortunately, `task` and `task-git` package
names are already taken.
> Add note about Arch Linux package

- completion/bash/task.bash
This fixes bash autocompletion that fails by producing an extra colon at the end of completions.  Note that there is a similar sed for colon removal already present in the zsh autocomplete
It also removes an unnecessary `sed 's/^\* //'` in favor of just using `print $2` in the awk command.
> Remove trailing colon from task listing

- watch.go
When I launch `task` with --watch option, occur context canceled occurs.
issue is here. https://github.com/go-task/task/issues/313
The cause was that it couldn't check custom error struct ([taskRunError](https://github.com/go-task/task/blob/master/errors.go#L21)).
this pr resolve it.
> suppress context errors when use watch option

- .goreleaser.yml
As mentioned in #325  config name_template is now file_name_template.
See https://goreleaser.com/deprecations/#nfpmsname_template for details.
> Fix name_template in Go Releaser

- cmd/task/task.go
pflag will output a "pflag: help requested" message after displaying the usage
if we don't explicitly  handle the flag.
> Have the --help/-h flag print usage.

- help.go
- internal/summary/summary.go
- internal/taskfile/task.go
- status.go
- task.go
- task_test.go
- testdata/label_list/Taskfile.yml
- testdata/label_status/Taskfile.yml
- testdata/label_summary/Taskfile.yml
- testdata/label_uptodate/Taskfile.yml
- testdata/label_var/Taskfile.yml
- variables.go
My attempt to solve issue described in #321 . Should work correctly though it needs review.
Simplest `Taskfile.yml` to demonstrate effects of this change:
```
version: '2'
tasks:
default:
deps:
- task: test
alias: "dep-foo"
cmds:
- task: test
alias: "foo-bar"
- task: test
test:
sources:
- Taskfile.yml
generates:
- Taskfile.yml
```
Output before:
```
task: Task "test" is up to date
task: Task "test" is up to date
task: Task "test" is up to date
```
Expected output with change:
```
task: Task "dep-foo" is up to date
task: Task "foo-bar" is up to date
task: Task "test" is up to date
```
Also there were some concerns if name "alias" is a good one for such property. Of the top of my head I have two other options: "name-override" or "label". Are these any better?
> Allow overriding the task name in the logger output

- completion/fish/task.fish
MacOS by default does not use gnu sed, which makes it not work. This patch will work with MacOS and also Linux
> Make fish completions compatible with MacOS

- docs/installation.md
- The default didn't work well for me out of the gate.
- This is the modified version to support passing in the arguments easily as well as an example for installing to `/usr/local/bin` for using in Codespaces or equivalent development workflow.
> feat: improve installation script documentation for shell installs

- docs/installation.md
Double -s argument does not make sense according to curl manual page.
-s stands for silent, while -S (capital S) stands for showing the error.
When used in combination, curl shows an error message if it fails, but disables progress meter.
Finally, in the end of sh command there is -d, which stands for debug and contradicts -sS curl arguments.
I suggest to remove curl silencers all together, because more debug is better in CIs.
I also suggest to use --location instead of -L for clarity.
> Update curl arguments in installation.md

- docs/usage.md
To make it a valid YAML file and avoid the error:
```
yaml: unmarshal errors:
line 6: mapping key "build" already defined at line 4
```
Also, mention `desc:` key in that section, as it's an important keyword.
> Fix duplicate task name on "Short task syntax" example

- watch.go
Watch wasn't working well for me. I started digging into it some and noticed that the `watcher` cli tool itself never had problems picking up changes for me.  Digging into how `task` is using watcher, I found a few things.
Top-level change explanation
1) My linter complained about the `return err` on line 44 was returning without cancel() being called.  I added this.
2) registerWatchedFiles was removing and adding files over and over to watcher.  Details below
Details on fix:
* While debugging, I added some print statements, and saw that this code kept removing and adding files to Watcher.  I didn't track down into Watcher itself, but this loop (going every second) in Taskfile seems to be the cause of making watch behavior not work well.
* Looking at the code it's unclear to me why …
> Make watch behavior work better

- .goreleaser.yml
- cmd/task/task.go
At present, when installing Task using `go install`, the version is reported as `master`.
```
$ go version
go version go1.16.3 darwin/amd64
$ go install github.com/go-task/task/v3/cmd/task@latest
$ task --version
Task version: master
```
As of Go 1.16, `go install` uses [module-aware mode by default](https://golang.org/doc/go1.16#go-command). As a result, the module version and checksum is stored within the binary.
```
$ go version -m $(which task)
/Users/jamie/go/bin/task: go1.16.3
path	github.com/go-task/task/v3/cmd/task
mod	github.com/go-task/task/v3	v3.3.0	h1:IfyT0z7a8ap4ag2nIDRkx+bkTN9S3AFED6SqBFnuHqU=
dep	github.com/fatih/color	v1.7.0	h1:DkWD4oS2D8LGGgTQ6IvwJJXSL5Vp2ffcQg58nFV38Ys=
dep	github.com/go-task/slim-sprig	v0.0.0-20210107165309-348f09dbbbc0 …
```
> Report Go module version and checksum

- .gitignore
- cmd/task/task.go
os.Kill is SIGKILL (kill -9), cannot be intercepted.
(see golang/go#13080)
Part of #458.
> signals: do not try to catch uncatchable signals

- docs/community.md
- docs/installation.md
The GitHub Actions action for installing Task has graduated from its original home in [the experimental `arduino/action` repository](https://github.com/arduino/actions) with a move to a dedicated permanent repository at [`arduino/setup-task`](https://github.com/arduino/setup-task).
This move was accompanied by [significant upgrades](https://github.com/arduino/setup-task/pulls?q=is%3Apr+is%3Aclosed) to the project infrastructure to facilitate its maintenance and quality assurance.
A [1.0.0 release](https://github.com/arduino/setup-task/releases/tag/v1.0.0) has been made and [a `v1` ref](https://github.com/arduino/setup-task/tree/v1) that will track all releases in the major version 1 series.
In addition to the name change, I have updated the example snippet to use this `v1` ref because …
> Update docs for new arduino/setup-task action repository

- internal/status/checksum.go
- internal/status/glob.go
- watch.go
Fixes https://github.com/go-task/task/issues/484
Exports internal/status.glob() and uses that for the watch globbing as well so that watch uses the task directory.
The only problem I see is that status.glob() never returns an error, while zglob.Glob() does, so the behavior will be changed beyond the intended scope. The only solutions I see are to re-implement the code from status.glob, change status.glob to return an error and thereby changing the behavior in other cases, or leave it be and accept the changed behavior of watch.
I prefer never silently ignoring errors, so I would change the behavior in other cases (checksum and timestamp checking), but it's not my call.
> Changes --watch to respect task directory

- completion/bash/task.bash
When trying to complete an argument that begins with a dash, the bash completion will potentially cause grep to output error messages:
For example, doing "task -d" followed by tabs in task source tree:
```
$ task -dgrep: option requires an argument -- 'd'
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
```
> Fix bash completions when the current argument begins with a dash

- completion/fish/task.fish
The existing fish completions are broken for any task names that contain a colon. The issue seems to be incorrectly parsing the output of `task -l` to replace all colons and spaces with tabs. For example,
This is how the list is currently parsed, 
```
➜ task -l | sed '1d' | grep docs:ico | awk '{ $1=""; print $0 }' | tr ': ', '\t' | string trim
docs    ico             Generate        favicon.ico     from    Logo.png
```
In this situation none of the `docs:*` tasks can be tab completed. The intention _seems_ to be to replace the string `': 
'` but it's not done correctly.
After these changes you can tab complete to each colon within a name like you'd expect,
```
➜ task -l | sed '1d' | grep docs:ico | awk '{ $1=""; print $0 }' | sed 's/:\ /\t/g' | string trim
docs:ico        Generate …
```
> Fix fish completions

- .github/workflows/release.yml
- .github/workflows/test.yml
- .goreleaser.yml
This enables `darwin-arm64` builds to support Apple Silicon-based Macs.
> Build with Go 1.16

- .github/workflows/release.yml
Upgrade Goreleaser action to version 2.
Because, it's impossible to use go-task with a M1 Mac.
With this version, I think that will fix the problem.
> Upgrade Goreleaser action to v2 - To ensure mac/m1 mac/arm release

- taskfile/read/taskfile.go
This change allows users to include Taskfiles inside the home directory. 
Paths beginning with the `~` character are expanded to absolute paths using `os.UserHomeDir()`
Example:
```yaml
version: "3"
includes:
common: ~/.task/Taskfile.yml
tasks:
default:
cmds:
- task: common:task1
- task: common:task2
- echo 'Finished.'
```
This references #185  and resolves #539
> Allow included Taskfiles to use ~/* paths

- task.go
- taskfile/task.go
- variables.go
Add the task parameter "interactive" to force interleaved output in order
to make interactive CLI apps work.
Feature request in #217
TODO:
* Update documentation
Signed-off-by: Marcello Sylvester Bauer <sylv@sylv.io>
> Task: Add interactive parameter

- .github/workflows/release.yml
- .goreleaser.yml
- fixed release to use a Personal Access Token: judging by history/blame, brew upload was disabled because it wasn't working, its likely because you need to use a PAT for it to work, check https://goreleaser.com/ci/actions/#token-permissions for more details
- added completion files to the archives
- installing the completions on the homebrew-tap
this should close https://github.com/go-task/homebrew-tap/pull/2 as well
> fix: goreleaser brew completions

- task.go
Fix #597
Check context error after running dependencies, to prevent false
negative precondition errors due to "context canceled".
> task: Check context error

- cmd/task/task.go
- help.go
- task.go
- task_test.go
- testdata/list_mixed_desc/Taskfile.yml
added an add'l cli option that lists all tasks, with or without description.
orig. behavior: task -l lists tasks with desc field
new behaviour: task -la or task -a will list all tasks. if task has desc, it will be included.
BREAKING CHANGES: none, that I know of.
NOTES/Concerns:
- This is wip.
- Haven't checked how it interacts with bash completion.
- The new Executor.TaskNames func does not use e.CompiledTask(taskfile.Call{Task: task.Task})
This relates to https://github.com/go-task/task/issues/383
> feat (help): allow cli option to list tasks with no description

- internal/execext/exec.go
- task_test.go
- testdata/dir/dynamic_var_on_created_dir/Taskfile.yml
This PR is to fix #481.
When a directory is specified on `dir` parameter in Taskfile, a file/directory not found error occurs when evaluating dynamic variables with the directory which does not exist.
That error shouldn't be raised because the specified directory will be created in later operations.
So I added some changes to avoid directory not found error.
> Avoid directory not found error in evaluating dynamic variables with newly created directory #481

- docs/community.md
Hi..
I've published JetBrains IntelliJ plugin for task.
Can you add the plugin link to the community page? 😄
> Update 'community.md' to add IntelliJ plugin link

- completion/bash/task.bash
1. 'compgen -c' lists _all_ command names on the system, which is not
appropriate for this script, furthermore echo does not read from stdin
so the output is lost.
2. use _get_comp_words_by_ref and __ltrim_colon_completions to handle task
names with colons.
"...modifying COMP_WORDBREAKS in your completion script is not safe
(as it is a global variable and it has the side effect of affecting
the behavior of other completion scripts"
Ref.: https://stackoverflow.com/a/12495727/7044304
3. Add options completion
4. Use task --list-all
> bash-completion refactoring

- taskfile/read/taskfile.go
This PR addresses issues mentioned in #498 
I've added `Taskfile.dist.yml` and `Taskfile.dist.yaml` to the list of default taskfiles to look for when including a directory.
> Add dist fallbacks to defaultTaskfiles

- .github/workflows/test.yml
- cmd/task/task.go
- docs/usage.md
- internal/output/group.go
- internal/output/interleaved.go
- internal/output/output.go
- internal/output/output_test.go
- internal/output/prefixed.go
- internal/output/style.go
- task.go
- task_test.go
- taskfile/merge.go
- taskfile/taskfile.go
- testdata/output_group/Taskfile.yml
Fixes #647
This allows CI systems that support grouping (such as with [GitHub Actions's `::group::` command](docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#grouping-log-lines) and [Azure Devops](docs.microsoft.com/en-us/azure/devops/pipelines/scripts/logging-commands?view=azure-devops&tabs=bash#formatting-commands)) to collapse all of the logs for a single task, to improve readability of log
The following Taskfile
```
version: 3
output:
group:
begin: "::group::{{ .TASK }}"
end: "::endgroup::"
tasks:
default:
cmds:
- "echo 'Hello, World!'"
```
Results in the following output
```bash
$ task
task: [default] echo 'Hello, World!'
::group::default
Hello, World!
::endgroup::
```
See [this GitHub Actions …
> Add support for begin/end messages with grouped output

- completion/zsh/_task
* List all current option flags
* Provide descriptions for every flag
* Pass the `task -l` descriptions as descriptions for the task completions
+ The prior logic had 4 invocations of sed and 1 of awk, and only kept the task name
+ Do all filtering in zsh without forking (except for `task` itself)
* When `--taskfile` is used, complete tasks from _that_ file
+ And otherwise, enable completions if only the `.dist` variant files are present
* Ensure mutually exclusive options preclude each other
+ the `+ '(groupname)'` clause defines this
* Fix `--dir` to take directories, not files
> completion: zsh: overhaul and sync to current flags

- cmd/task/task.go
- help.go
- task.go
#310 was closed recently in favor of the much better shell-completion refactor of #671.
However, #310 included useful functionality that has been lost in the process – specifically the capability to list only task names (without descriptions and without `*` decorations), which, like @shilangyu pointed out, is useful for more than just shell completions; IDE integration, CI/CD tooling, and SCM/container tooling to name a few.
- This PR reintroduces that capability without any changes to the shell-completion scripts. 
- The capability was modified to support the new `--list-all, -a` flag such that: 
- `task --list --silent` (`task -ls`) will print only task names that have a description
- `task --list-all --silent` (`task -as`) will print all task names
- The review comments from the …
> Add capability to print only task names

- completion/fish/task.fish
When you are in a directory where there is no `Taskfile.yaml`, the completion will go crazy and keep adding new line on every `Tab` keypress.
```
 task task: No Taskfile found in "/mnt". Use "task --init" to create a new one
tatask task: No Taskfile found in "/mnt". Use "task --init" to create a new one
tatask task: No Taskfile found in "/mnt". Use "task --init" to create a new one
tatask task: No Taskfile found in "/mnt". Use "task --init" to create a new one
tatask task: No Taskfile found in "/mnt". Use "task --init" to create a new one
tatask -l
```
This will silence the error when there's nothing to complete. Of course it will still show completion when there is a `Taskfile.yaml` file.
> Fix broken completion when no taskfile is found

- docs/usage.md
A task name is missing in the example.
> Fix interactive task example

- .editorconfig
- completion/bash/task.bash
- completion/fish/task.fish
As task is a very generic name that conflicts with for example
taskwarrior, some packagers might choose to change it. See my package in
the AUR: https://aur.archlinux.org/packages/go-task.
This change makes it easier to configure the name for downstream
packagers.
> Make progname easier to configure in task.{bash,fish}

- docs/docs/api_reference.md
- docs/docs/community.md
- docs/docs/donate.md
- docs/docs/releasing.md
- docs/docs/styleguide.md
- docs/docs/taskfile_versions.md
- docs/docusaurus.config.js
This PR adds a new page to the documentation with CLI and schema API reference.
The idea was from @abrahammurciano, and it makes total sense.
This will only be published to https://taskfile.dev once this reaches the master branch. For now, you can preview this page here: https://preview-taskfile.netlify.app/api/
Let me know if you have any additional suggestions.
> taskfile.dev: Add page with API Reference

- cmd/task/task.go
- errors.go
- task.go
- task_test.go
- testdata/error_code/Taskfile.yml
- watch.go
Hello,
I recently found the need to get the return code that was returned from a failed command from a task's cmds. After investigating quickly it appeared to me that the task tool would always return with status code 1 when an error occurred during a task.
This PR proposes an additional command flag (--carry), false by default, that will carry the error code, if any, over to the calling shell.
> Add --exit-code (-x) flag to enable carrying error codes from task cmds

- .gitignore
- CHANGELOG.md
- Taskfile.yml
- cmd/sleepit/sleepit.go
- cmd/task/task.go
- internal/execext/exec.go
- signals.go
- unix_test.go
Task will now give time for the processes running to do cleanup work
Ref #458
Ref #479
Fixes #728
> Fix behavior of interrupt (SIGINT, SIGTERM) signals

- docs/docs/usage.md
Our example was not using the correct syntax required for grouping
command output on GHA.
Documentation at https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#grouping-log-lines
> Fix GHA grouping examples

- docs/docs/usage.md
The text above this block currently references a `timestamp` method for checking if a task should be run, then the example uses `checksum` instead.
> Correct `method: timestamp` example block in usage docs

- completion/zsh/_task
Use --list-all instead of --list in order include tasks without
description in the auto-completion.
> Fix Zsh completion for tasks without description

- docs/docs/usage.md
> Vars declared in the included Taskfile have preference over the included ones!
is a contradiction. It should be
> Vars declared in the included Taskfile have preference over the variables in the including Taskfile!
> Resolve contradiction.

- .goreleaser.yml
This should make it easier to generate the same builds locally (tested with --snapshot).
https://goreleaser.com/customization/build/#reproducible-builds
> Modify goreleaser defaults for reproducible builds

- completion/bash/task.bash
Some incremental update. Point 1 below was most annoying during daily use.
Features:
- Handles the -t and -d options correctly, i.e., completes with tasks in the target directory.
- Calls the correct binary for completions, if bound multiple times, by using `$1` or `COMP_WORDS`.
> Improved bash completion

- completion/bash/task.bash
This is a small update of PR <https://github.com/go-task/task/pull/835>.
I may have missed the `--silent` option which is much better suited to get the list of tasks than digging in output intended for human readers with regular expressions.
> Use --silent to get the list of tasks (bash completion)

- docs/docs/releasing.md
Since published release executables can now be locally reproduced and verified (see #832, tested with latest release v3.15.0), I would mention it in the docs.
> Document how to reproduce release binaries

- taskfile/read/dotenv.go
This PR fixes #858 - A bug (introduced in f45dd11) that causes an "is a directory" error when a taskfile contains a `dotfiles` key with unresolved variable.
The bug exists because the new `e.setCurrentDir()` function is setting `e.Dir` to the taskfile's root directory where it was previously `""`. When this variable was empty and the given dotfile was also empty, `os.Stat` would have returned an `os.ErrNotExist` and the loop would have `continued`. However, now that `e.Dir` is set to the taskfile directory, this `os.Stat()` check passes (as the directory exists) and the `godotenv.Read()` function errors causing the program to fail.
This fix simply checks if each value in the list of `dotfiles` is empty (not set) and `continues` if it is. This allows users to continue using the behaviour …
> fix: ignore empty dotfile file names

- completion/bash/task.bash
Improvements:
1. Do not attempt to propose completions if the current position is behind `--` as the arguments would go to task's `CLI_ARGS` variable.
2. Only use the command-line before `--` when proposing task names to prevent the list option from going to task's `CLI_ARGS` variable.
> Fix handling of CLI_ARGS

- completion/zsh/_task
This makes the zsh completion list configurable through an env variable exposed before sourcing the completion script without changing current behavior.
The var name is taken from the [bash completion script](https://github.com/go-task/task/blob/master/completion/bash/task.bash#L3) which seems to provide similar functionality.
Add:
```sh
export GO_TASK_COMPLETION_LIST_OPTION="--list"
```
To limit autocompletion suggestions to only tasks with descriptions.
> Make zsh completion list configurable

- docs/docs/usage.md
- errors.go
- help.go
- task.go
- task_test.go
- taskfile/included_taskfile.go
- taskfile/merge.go
- taskfile/read/taskfile.go
- taskfile/task.go
- testdata/includes_internal/Taskfile.yml
- testdata/includes_internal/Taskfile2.yml
- testdata/internal_task/Taskfile.yml
- variables.go
Building on the fantastic work introduced by #656, I have been refactoring some of my projects with a `taskfiles` subdirectory. This helps me manage my extemely long files much more effectively and also allows me to take full advantage of the namespacing features (`a:b:c`).
However, I've noticed that in my more complex projects, the `--list-all` output is now _extremely_ long, as some of my "utility" taskfiles are being included in multiple other taskfiles. I've provided a simplified example below:
```yaml
version: '3'
includes:
install: ./taskfiles/Install.yml
gen: ./taskfiles/Gen.yml
```
```yaml
version: '3'
tasks:
proto-tools:
mock-tools:
```
```yaml
version: '3'
includes:
install: ./Install.yml
tasks:
protos:
deps:
- install:proto-tools
mocks:
deps:
- install:mock-tools
```
```ini
* …
```
> Internal tasks

- .gitignore
- CHANGELOG.md
- Taskfile.yml
- docs/docs/installation.md
- docs/docs/releasing.md
- package-lock.json
- package.json
Closes #870
TODO:
We're using our own fork, at least for now: https://github.com/go-task/go-npm.
Package published at: https://www.npmjs.com/package/@go-task/cli.
> Add package.json to allow users to install Task using npm

- docs/docs/usage.md
Resolves #788 by added a couple of paragraphs and a code-example that clearifies that `sources` / `generates` and `status` can be used in the same task.
I'm not sure whether the code-example should have been even more generic, or the (slightly simplified) real-life example borrowed from https://github.com/go-task/task/pull/477#issuecomment-867808366 is ok?
> Clearify that sources/generate and status can be used together

- help.go
- task_test.go
> Fix task names for `--list` and `--list-all`

- CHANGELOG.md
- help.go
- internal/logger/logger.go
- internal/summary/summary.go
@andreynering @orenmazor This seemed like low-hanging fruit, so I've done a quick first draft (see the [associated branch](https://github.com/go-task/task/tree/845-colorize-output) and screenshots:
`task --list-all`:
`task foo --summary`:
Let me know what you think of the colours - I'm happy to change them. I went with: 
- `green` for tasks as this matches the green when running a task
- `cyan` for descriptions as it complements the green (and the Task logo)
- `yellow` for commands
Could we do something more interesting with namespaces? Each layer of the namespace be a different colour? This might be too noisy... Or maybe just a different colour for the colons?
---
Sidenote: I noticed that `logger.Outf` automatically adds a `\n` to the input string. I'm not a fan of this behaviour as it …
> Colorize --list, --list-all and --summary output

- .gitignore
Now that [Fleet is in open preview](https://blog.jetbrains.com/fleet/2022/10/introducing-the-fleet-public-preview/), just pre-empting the inevitable and adding the fleet config directory to the `.gitignore`.
Sidenote: To anyone who hasn't tried it, I recommend giving it a go. I'm a long time VSCode user (and I'm not the biggest fan of JetBrain's IDEs for Golang development). However, this looks like a very strong start, despite lacking a lot of functionality today (plugins, split panes, auto-imports etc). Hopefully, with time, this will become a viable alternative to VSCode.
> Ignore fleet configuration directory

- .editorconfig
- completion/fish/task.fish
- Added check for non-zero exit code of `task --list-all` that happens if there is no `Taskfile` present or etc.
- Added comments
- Added fish to `.editorconfig`
> Improved fish shell completions

- errors.go
- go.mod
- go.sum
- help.go
- setup.go
- task.go
- variables.go
This PR closes issue #867.
If the fuzzy model fails to find the most similar task name, it will just say "task does not exist" and the suggestion message won't be shown
> Suggest the most similar task name when a given task does not exist

- docs/docs/installation.md
Hi! Following this issue https://github.com/go-task/task/issues/293, I created this PR to document current task completion installation.
Here is a screenshot of the added section.
> Document completion installation

- completion/ps/task.ps1
this is a completion script only change, you can copy the powershell script to local to use it get merged and released
( `<tab>` is for <kbd>Tab</kbd> input)
```
❯❯ ~\..\..\task git:(master) task l<tab>
clean          docs           lint           npm            sleepit        test-release
default        install        mod            packages       test
```
`task l<tab>` -> `task lint`
OR show prefix matches
```
❯❯ ~\..\..\task git:(master) task d<tab>
default   docs
```
as for `:` splited sub task
`task do<tab>` -> `task docs`
`task docs<tab>` -> `task docs:`
then
```
❯❯ ~\..\..\task git:(master) task docs:<tab>
docs:build       docs:changelog   docs:clean       docs:deploy      docs:setup       docs:start
```
and current output format of `--list-all` make it hard to support sub task …
> make powershell completion works to fill task name

- .github/workflows/issue-awaiting-response.yml
- .github/workflows/issue-needs-triage.yml
This is a first attempt to take some of the burden off managing issues/labels with a bit of automation. This PR adds 2 simple workflows:
- `issue-needs-triage` - Adds a `needs-triage` label to new issues so that we can track issues that haven't been reviewed/labelled by a maintainer yet.
- `issue-awaiting-response` - Will automatically remove the `awaiting response` label when the issue author responds.
Screenshot below from my private test repo
> feat: add actions to auto label issues

- docs/docs/contributing.md
Small update to the contribution guide now that https://github.com/SchemaStore/schemastore/pull/2565 is merged.
> chore: add schema info to contribution guide

- task_test.go
- taskfile/read/taskfile.go
- testdata/includes_shadowed_default/Taskfile.yml
- testdata/includes_shadowed_default/Taskfile2.yml
- testdata/includes_shadowed_default/file.txt
- testdata/includes_unshadowed_default/Taskfile.yml
- testdata/includes_unshadowed_default/Taskfile2.yml
- testdata/includes_unshadowed_default/file.txt
I was experimenting with refactoring my (now very large) Taskfile into smaller, more manageable files and I came across #661. This functionality would really help us to make our tasks a bit simpler.
This PR adds the functionality mentioned by @tylermmorton and @andreynering in that issue. Namely:
- When a Taskfile with a `default` task inside is included, the `default` task is available by calling `task <namespace>` as opposed to `task <namespace>:default`.
- If the parent Taskfile contains a task with the same name as the namespace (i.e. the task is "shadowed"), the task in the _parent_ is run, and _not_ the default task in the included file.
- This ensures that we maintain backward compatibility with existing Taskfiles.
- A couple of unit tests for ensuring the functionality works going …
> feat: run default task in included file when task is omitted

- CHANGELOG.md
- cmd/task/task.go
- help.go
- task.go
- task_test.go
- testdata/alias/alias-duplicate.txt
This PR refactors the code used to fetch the list of tasks when outputting them to the CLI. This is used for the `--list` and `--list-all` flags as well as when any errors are displayed to the user.
This code has a lot of duplication in it and isn't very extensible. i.e. it requires a lot of custom code and bloat to add new features.
I've added a `GetTaskList` function to the executor (this nicely matches the new `GetTask` function in #879). This function will return a sorted list of tasks from the task map and filter any tasks according to the list of given filters. These filters can be any function that matches the new `FilterFunc` type. 
I have implemented the two filter functions that are currently required in the codebase: 
- `FilterNoDesc` - Removes tasks with no description
- …
> refactor: implement task list filtering

- help.go
This PR adds aliases to the `--list`/`--list-all` flags when combined with `--silent`.
I wasn't 100% sure about this one, but I tried to tab-complete an aliased task today and it didn't work. Do we think that users should be able to tab complete aliased tasks or is this not needed because tab-completion will fill in the long name anyway? Thoughts appreciated.
> feat: include aliases in --list --silent output

- docs/static/schema.json
`schema.json` Workaround for these two JetBrains issues:
- [IDEA-236928 json schema: False positive "Schema validation: Validates to more than one variant" with "oneOf"](https://youtrack.jetbrains.com/issue/IDEA-236928)
- [IDEA-265710 JSON schema validation fails if anyOf is nested in oneOf](https://youtrack.jetbrains.com/issue/IDEA-265710)
There is no material effect on the actual schema validation, as the `oneOf`/`allOf` evaluates only one list entry.
`allOf([1])` is `1`, and `oneOf([1])` is also `1`.
Fixes #847
> JetBrains JSON Schema Validator Error Workaround

- cmd/task/task.go
- help.go
- internal/editors/output.go
- task.go
- task_test.go
a new `--json` flag works only with the `--list` and `--list-all` flags to format those task lists as JSON output.
- can't use `--json` by itself:
```
go run ./cmd/task --taskfile ./testdata/output_group/Taskfile.yml hello --json | jq .
task: --json only applies to --list or --list-all
exit status 1
```
- `--json --list` ignores tasks that are missing descriptions:
```
go run ./cmd/task --taskfile ./testdata/output_group/Taskfile.yml hello --json --list | jq .
{
"tasks": []
}
```
- `--json --list-all` includes all tasks
```
go run ./cmd/task --taskfile ./testdata/output_group/Taskfile.yml hello --json --list-all | jq .
{
"tasks": [
{
"name": "bye",
"desc": "",
"summary": "",
"up_to_date": false
},
{
"name": "hello",
"desc": "",
"summary": "",
"up_to_date": false
}
]
}
```
this PR includes …
> feat: add --json flag to be used by editor extensions

- .golangci.yml
- internal/output/output_test.go
- watch.go
I noticed that you added `goimports` as a linter. This change extends that by forcing users to separate internal imports (ones starting with `github.com/go-task/task`) from other non standard lib imports. This is a pattern followed elsewhere in the project, but not currently enforced.
VSCode users can add this to their settings to do this formatting automatically:
```jsonc
{
"gopls": {
"formatting.local": "github.com/go-task/task",
}
...
}
```
> feat: add local-prefixes flag to goimports linter

- taskfile/read/taskfile.go
Properly close `Taskfile.yml` after reading it.
This should fix issues preventing modifications to the Taskfile while tasks are still running, like switching git branches for example.
Fixes #963
> Close Taskfile after reading it

- .github/workflows/issue-awaiting-response.yml
- .github/workflows/issue-closed.yml
Small addition to the GitHub actions to tidy up `needs triage` labels if someone closes an issue before it is triaged.
Screenshot from my test repo below:
No change if issue has already had the `needs triage` label removed:
> feat: add action for when an issue is closed

- CHANGELOG.md
- cmd/task/task.go
- task.go
- taskfile/taskfile.go
- watch.go
Fixes #969 by setting the default value of the pflag to 0 instead of "5s".
Additionally, this PR changes both the `Taskfile` struct and the `interval` flag variable to use `time.Duration` directly rather than a string. This still allows the user to pass values using "5s" or "500ms" etc, but defers the passing of the value to the yaml and pflag libraries respectively. This slightly simplifies the `watch.go` file.
> fix: watch interval

- CHANGELOG.md
- taskfile/merge.go
Fixes #961.
This problem occurs when a user uses `version: '2'` in their Taskfile in combination with a `Taskfile_{{OS}}.yml` file. In the case of #961, I'm guessing there was only a `Taskfile_windows.yml` file which is why the issue doesn't repro on Linux.
This happens because the `Merge` function is called with `includedTaskfile` set to `nil`:
https://github.com/go-task/task/blob/5be1f6bb2b612eeeae21a1c5bea6e7cd0e0f852e/taskfile/read/taskfile.go#L171-L182
This value is then not being nil checked in the `Merge` function here:
https://github.com/go-task/task/blob/5be1f6bb2b612eeeae21a1c5bea6e7cd0e0f852e/taskfile/merge.go#L48
The fix simply adds a nil check to this line.
> fix: add missing nil check

- docs/docs/api_reference.md
- docs/docs/usage.md
- docs/static/schema.json
- task.go
- task_test.go
- taskfile/cmd.go
- taskfile/platforms.go
- taskfile/task.go
- testdata/platforms/Taskfile.yml
- variables.go
This is a draft PR based on the discussions in #978. It allows limiting a task or a command to a particulate OS/Arch combination. It also validates any given OS/Arch against a list of valid values.
Example Taskfile that is valid with this PR:
```yaml
version: '3'
tasks:
build-windows:
platforms: [windows]
cmds:
- echo 'building on windows'
build-darwin:
platforms: [darwin]
cmds:
- echo 'building on darwin'
build-mixed:
cmds:
- cmd: echo 'building on windows/arm64'
platforms: [windows/arm64]
- cmd: echo 'building on linux/amd64'
platforms: [linux/amd64]
- cmd: echo 'building on darwin'
platforms: [darwin]
```
Todo:
- Add test for `testdata/platforms `
- Update documentation
> Add support for 'platforms' in both task and command

- help.go
- task.go
This PR makes some optimizations to the task filtering. It's currently extremely slow on complex configs. Particularly in setups with many files that include one another.
- Use goroutines for each compilation
- Filter before compiling a task
- Simplify filtering API
- Handle fast compile errors
---
Edit: Some context, this takes one of my more complex Taskfiles from around 4 seconds to compile the tasks, to around 0.5s!
> Optimize task filtering

- docs/docs/usage.md
- internal/status/checksum.go
- internal/status/checksum_test.go
- internal/status/timestamp.go
- status.go
Fixes #976 
> I noticed that the `timestamp` method doesn't seem to work. It reruns the tasks all the time even though nothing has changed. 
> 
> This happens when the task generates some artifacts in the first run and doesn't re-generate them in the subsequent runs. This causes the following run to return `false`.
> https://github.com/go-task/task/blob/63c50d13eec142694ff5a074c3f9cda6c53d8be3/internal/status/timestamp.go#L41
> 
> To fix this issue, `task` should include the last run time in the `generates`. This way, the time of the generates will be newer than the sources, and so there is no need for rerunning. 
> 
> 
> This solution
> - would also fix the issue with an empty `generates` array. 
> - is consistent with the `checksum` method, and these two should work the same in most …
> fix: avoid reruns when the timestamp method is used

- CHANGELOG.md
- taskfile/included_taskfile.go
- taskfile/merge.go
Given the following file structure:
```
├── tasks
│   ├── bar.yml
│   └── foo.yml
└── Taskfile.yml
```
and the contents:
```yaml
version: '3'
includes:
included: ./tasks/included.yml
```
```yaml
version: '3'
includes:
util:
taskfile: ./util.yml
internal: true
tasks:
pwd:
cmds:
- pwd
util-pwd:
cmds:
- task: util:pwd
```
```yaml
version: '3'
tasks:
pwd:
cmds:
- pwd
```
The following output is expected:
```sh
> task --list-all
task: Available tasks for this project:
* bar:default:             (aliases: bar)
* foo:default:             (aliases: foo)
```
However, we get this instead:
```sh
> task --list-all              
task: Available tasks for this project:
* foo:default:             (aliases: foo)
```
In `merge.go` we are merging the included taskfile struct into the parent's struct. This …
> fix: tasks being incorrectly marked as internal

- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- CHANGELOG.md
- go.mod
- go.sum
Updates the repo from 1.18/1.19 to 1.19/1.20.
Also:
- Updates the [golang.org/x/exp](https://pkg.go.dev/golang.org/x/exp) package (which we use for `slices`) to the latest commit.
- Updates `golangci-lint` to 1.51.1 in order to solve [this issue](https://github.com/golangci/golangci-lint/issues/3107).
> chore: update to go 1.20

- CHANGELOG.md
- docs/docs/api_reference.md
- internal/logger/logger.go
- We now all use CI-solutions and many of them supports terminal colors in browser (logs, web-terminal and others)
- All CI processes are no-tty and can't pass check `isatty.IsTerminal` (`fatih/color` forces `nocolor` for all CI jobs  with condition `!isatty.IsTerminal(os.Stdout.Fd())`)
- CI jobs without colored logs extremely inconvenient for debugging and evaluating results
Now, we can force colored output with `FORCE_COLOR` environment variable and ignore all shortsighted restrictions and efficiently use the awesome `go-task/task` in CI jobs.
Maintainer of [fatih/color](https://github.com/fatih/color/issues/155) rejected PR with `FORCE_COLOR` support with unconvincing arguments
> feat(logger): add FORCE_COLOR environment variable support

- docs/static/schema.json
Fix the output option to match implementation and documentation.
> Fix output "prefixed" option in schema.json

- cmd/task/task.go
- go.mod
- go.sum
- setup.go
- task_test.go
- taskfile/merge.go
- taskfile/read/taskfile.go
- taskfile/taskfile.go
- variables.go
Simple change to switch back to using the [Masterminds/semver](https://github.com/Masterminds/semver) package for storing/comparing the Taskfile schema version.
Also see [this related PR](https://github.com/Masterminds/semver/pull/196) which may make some of our comparisons a bit more readable.
> feat: use semver package for taskfile schema version

- CHANGELOG.md
- status.go
Original [issue](https://github.com/go-task/task/issues/840) and [PR](https://github.com/go-task/task/pull/1035).
This PR fixes the `status` and `sources` implementation. Rather than optimising the boolean logic, I chose to make the code easier to read and understand. This should make it easier to maintain in the future.
Truth table for `status` and `sources`:
| Status up-to-date | Sources up-to-date | Task is up-to-date |
| ----------------- | ------------------ | ------------------ |
| not set           | not set            | ❌                 |
| not set           | ✔️               | ✔️               |
| not set           | ❌                 | ❌                 |
| ✔️              | not set            | ✔️               |
| ✔️              | ✔️               | ✔️               |
| ✔️ …
> fix: status and sources

- cmd/task/task.go
- docs/docs/api_reference.md
- docs/docs/usage.md
- docs/static/schema.json
- internal/output/group.go
- internal/output/interleaved.go
- internal/output/output.go
- internal/output/output_test.go
- internal/output/prefixed.go
- task.go
- task_test.go
- taskfile/output.go
- testdata/output_group_error_only/Taskfile.yml
Implementation idea for #664.
> Describe your changes 
```yaml
version: '3'
silent: true
output:
group:
error_only: true
tasks:
passing: echo 'passing-output'
failing: echo 'failing-output' && exit 1
```
```sh
> task passing
(no output)
> task failing
failing-output
task: Failed to run task "failing": exit status 1
```
Enrich `Group` output by an `error_only` flag which should swallow the output (stdout + stderr) if any external command did not have a non zero exit code. By default this flag is disabled.
Changes should not interfere with task files created in previous versions as the default behavior is not changed.
I would love to have some feedback if this goes into the right direction. If so, I would love to continue working on it.
> Feature 664 group error only

- CHANGELOG.md
- cmd/task/task.go
- docs/docs/api_reference.md
- docs/docs/usage.md
This is an idea that has been in my mind for some time. Feedback and/or suggestions are welcome.
In short, this adds the ability to run a Taskfile from your home directory (`$HOME/Taskfile.yaml`), meaning that you can now have a Taskfile that you can run from anywhere with a simple `task -g ...`.
> Add `--global` (`-g`) flag

- docs/docs/installation.md
- go.mod
Task has generic code in it now which requires 1.18 and so will not build on version 1.15 any more. Also, we only officially support the last 2 versions of Go and 1.15 is now 5 versions (2.5 years) old.
Therefore, I have removed the docs for installing on 1.15 or older and added some text about the minimum required version. Instead of statically typing this in the docs, I've linked to the `go.mod` so that we don't have to remember to update the docs and moved the `go` version to the top of the `go.mod` file so the line reference won't change.
> chore: remove installation docs for Go 1.15

- CHANGELOG.md
- docs/docs/changelog.md
- docs/docs/usage.md
- internal/templater/funcs.go
- task_test.go
- testdata/split_args/Taskfile.yml
close #1040 
This PR adds a new splitArgs template function
example:
```yaml
version: '3'
tasks:
default:
cmds:
- cmd: echo '{{splitArgs "foo bar 'foo bar baz'"}}'
```
> Add splitArgs template function

- .github/workflows/sync-translated-documents.yml
- docs/Taskfile.yml
- docs/crowdin.yml
- docs/docusaurus.config.js
- docs/i18n/en/code.json
- docs/i18n/en/docusaurus-plugin-content-docs/current.json
- docs/i18n/en/docusaurus-theme-classic/footer.json
- docs/i18n/en/docusaurus-theme-classic/navbar.json
- docs/i18n/zh-Hans/code.json
- docs/i18n/zh-Hans/docusaurus-plugin-content-blog/authors.yml
- docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current.json
- docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/api_reference.md
- docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/changelog.md
- docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/community.md
- docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/contributing.md
- docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/donate.md
- docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/faq.md
- docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/installation.md
- docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/intro.md
- docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/releasing.md
- docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/styleguide.md
- docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/taskfile_versions.md
- docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/usage.md
- docs/i18n/zh-Hans/docusaurus-theme-classic/footer.json
- docs/i18n/zh-Hans/docusaurus-theme-classic/navbar.json
- docs/package.json
- docs/yarn.lock
It mainly solves the problems mentioned in [Help site supports multiple languages](https://github.com/go-task/task/issues/1057), and the specific work is as follows:
Resolve: https://github.com/go-task/task/issues/1057
Preview: https://misitebao-taskfile-git-feature-1057-support-mu-5d0af6-misitebao.vercel.app/
> feat: support multiple languages and add Chinese translation

- CHANGELOG.md
- internal/fingerprint/sources_checksum.go
- task_test.go
Fixes #1076. FWIW, I don't think this ever worked as the test was checking for the value that is always returned.
Original feature PR: https://github.com/go-task/task/pull/216
> fix: checksum variable in status is incorrect

- CHANGELOG.md
- taskfile/cmd.go
- taskfile/copy.go
- taskfile/dep.go
- taskfile/platforms.go
- taskfile/precondition.go
- taskfile/task.go
This is another piece of work that has fallen out of my changes in the `dag` branch. AFAIK This doesn't cause any issues currently. However, it is causing issues on my `dag` branch and I see no reason to delay merging the fix while I work on other things.
Deep copying currently isn't working as intended when a slice contains pointers. This PR fixes this by adding a `DeepCopier` interface which allows you to specify how a type should be deep copied. If a slice type implements this interface then the `DeepCopy()` function will now be called on each element. This gives us the ability to recurse into our structures and deep copy everything. Many of our types already satisfy this interface. However, I have added a method to the remaining ones that didn't.
I did consider using a 3rd party …
> fix: deep copying pointers inside slices

- .github/workflows/sync-translated-documents.yml
- .github/workflows/upload-source-documents.yml
> chore: update workflows

- CHANGELOG.md
- Taskfile.yml
- cmd/release/main.go
I noticed that the npm version bump was added to the Taskfile. I figured that we could just add this to the new release tool so now `task release -- major|minor|patch|x.x.x` will bump the changelog _and_ yarn files.
> feat: release tool improvements

- task.go
- task_test.go
- testdata/status/Taskfile.yml
As discussed in #546 this pull-request updates the condition surrounding the "up to date" message emitted from the status-check to now also respect the task-level silence flag. It also allows the user to switch off silence via the Verbose flag.
I view this more as a fix than a new feature so I have not added any documentation. I'll be happy to do so if it is deemd nessecary.
> fix: status-checks should respect task and global silent-mode

- internal/output/output_test.go
- task_test.go
- taskfile/platforms_test.go
- taskfile/precondition_test.go
- taskfile/taskfile_test.go
- watch_test.go
Uses [`github.com/stretchr/testify/require`](https://github.com/stretchr/testify/require) to test errors instead of [`github.com/stretchr/testify/assert`](https://github.com/stretchr/testify/assert). This applies to both `NoError` and `Error` functions.
This means that execution of the test will stop if we get an into an unexpected state and it will stop further cascading error assertions from obscuring the root cause.
The `assert` package is still used everywhere else as this means that we can see when multiple values are incorrect if the test is in a "good" state.
> refactor: use require for testing errors

- CHANGELOG.md
- args/args_test.go
- cmd/task/task.go
- docs/docs/api_reference.md
- help.go
- internal/deepcopy/deepcopy.go
- internal/orderedmap/orderedmap.go
- internal/orderedmap/orderedmap_test.go
- internal/output/output_test.go
- internal/sort/sorter.go
- internal/sort/sorter_test.go
- internal/summary/summary.go
- internal/summary/summary_test.go
- setup.go
- task.go
- task_test.go
- taskfile/cmd.go
- taskfile/merge.go
- taskfile/read/dotenv.go
- taskfile/read/taskfile.go
- taskfile/task.go
- taskfile/taskfile_test.go
- taskfile/tasks.go
- taskfile/var.go
- variables.go
Fixes #946
This PR implements custom sorting for tasks using a new `--sort` flag. This will work with any of the commands that output a list of tasks. i.e.
- `task --list`
- `task --list --silent`
- `task --list --json`
- `task --list-all`
The `--sort` flag will accept a string that specifies the sort order. The following values are supported:
- `default` - The same as `alphanumeric`, but root tasks (with no namespace) will be always appear first.
- This is the current sorting behavior 
- `none` - No sorting. Tasks will appear in the order they are defined in the taskfile
- If multiple taskfiles are used, they will be traversed in lexicographical order of the taskfile path.
- `alphanumeric` - Sorts tasks alphabetically by name ignoring the files they are defined in.
The implementation for …
> feat: implement task sorting with `--sort` flag

- completion/fish/task.fish
The existing fish completions script is broken when tasks include aliases. This change adds an additional sed replacement to match against commands with aliases.
Here's an example recording with the existing completions, then sourcing and using this fixed version: https://asciinema.org/a/jVlyeadd643J6FC3o5V6927hM
> Fix fish completions for tasks with aliases

- cmd/task/task.go
- help.go
- internal/compiler/v2/compiler_v2.go
- internal/compiler/v3/compiler_v3.go
- internal/fingerprint/status.go
- internal/logger/logger.go
- internal/summary/summary.go
- precondition.go
- signals.go
- task.go
- watch.go
As discussed in #1110.
Simply makes line endings consistent in our format printers which gives a bit more control to the caller of the function.
> refactor: remove newlines from formatter print functions

- .github/CONTRIBUTING.md
- docs/docs/contributing.md
Just spotted that our `.github/CONTRIBUTING.md` hasn't changed for 6 years. It should probably point to our new contribution guide so that first-time contributors are linked there by GitHub automatically.
> chore: update github contribution file

- help.go
Small bug introduced in #1137 (not yet released) which stopped the usage/help text from using the tabwriter. This stopped it from printing in nice columns.
> fix: tabwriter in usage output

- cmd/task/task.go
Fixes #1141
I think this PR is a nice, clean solution to the problem. Unfortunately, as you can see, it also has the side-effect of removing the red coloured text from the error message since the executor/logger are out of scope in `main` 🙁 I'm not sure what the best solution is for this. We weren't always consistent with showing errors in coloured text anyway.
- We could potentially return the executor/logger back to the main function and use the logger that way. However, the logger isn't actually setup until we call `e.Setup()` and errors can occur before that which would result in nil pointer panics.
- We could just not use the logger at all and print a raw ANSI code to get the color, but we'd need to build in cases for the `--color` flag and `NO_COLOR` envvar.
@andreynering wdyt? …
> Fix duplicate error message

- completion/ps/task.ps1
>
>
Didn't know there is a command `task --list-all --json/--silent` for all available tasks when I submit last PR.
Previous, if your pwd have a dir or file named `gen` or `gen...`, and you have a task named `gen`,
when you type `task gen<tab>`, powershell will fallback to filepath complete, and your input will become `task .\gen`
after this pr, `task gen<tab>` are still `task gen`
File path auto completion still works with `.\<tab>` or `./<tab>`
> powershell completion: disable file path autocomplete / add flags

- docs/docs/api_reference.md
- docs/docs/usage.md
- docs/static/schema.json
- task.go
- task_test.go
- taskfile/call.go
- taskfile/cmd.go
- taskfile/dep.go
- testdata/silent/Taskfile.yml
- variables.go
This PR addresses #680 by fixing a behaviour and introducing a small new feature.
Task now support silencing calls to other calls. The `Cmd` struct already had a Silence field, but it did not actually silence the "task: " output that is produced whenever a task is invoked.
The fix has been implemented by expanding the [`Call`](https://github.com/danquah/task/blob/21a8bb025ba733616cb3abbf84b35a2a82522d74/taskfile/call.go) struct to now also pass a ´Silent` field.
Dependencies are also a type of `Call` and to stay consistent the `Dep` struct has also been expanded with a `Silent` field.
> Silenced Calls

- internal/fingerprint/sources_checksum.go
- task_test.go
Resolves https://github.com/go-task/task/issues/1185.
I verified that the test case fails on main as well.
> fix: only rewrite checksum files if the checksum has changed

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- CHANGELOG.md
- setup.go
- task_test.go
Added a warning to the output when using a `version: 2` schema. (This functionality was split out of #1198).
This might break things for people using v2 schemas in scripts if they update... we could stop output if the `--silent` flag is specified, but this might not stop it from breaking where some tasks have `silent: true`. Maybe we send the output to stderr instead? Thoughts welcome.
> feat: add a deprecation warning when running Taskfiles with a v2 schema

- docs/docs/faq.md
- docs/docs/styleguide.md
Fixes #1115 by adding a section to the FAQ and Styleguide about not being able to reuse shells in a Task's commands.
> docs: add comments from #1115 to faq and styleguide

- docs/src/css/custom.css
Make light theme less white and dark theme less black. I find the legibility better with a slightly reduced contrast. This in a work in progress ™️. Opening to PR to get a quick opinion, maybe additional suggestions.
We can keep improving with time. Our theme is very basic currently, mostly identical to Docusaurus' default one.
/cc @pd93 @misitebao
> chore(website): update website colors

- cmd/task/task.go
- docs/docs/experiments/experiments.md
- internal/experiments/experiments.go
This PR adds support for experimental feature environment variables. This follows the design discussed in the [breaking changes proposal](https://github.com/go-task/task/issues/1191).
Environment variables can be specified in 3 ways:
1. Using the relevant environment variable in front of a task command. For
example, `TASK_X_<FEATURE>=1 task <my-task>`. This is intended for one-off
invocations of Task to test out experimental features.
1. Using the relevant environment variable in your "dotfiles" (e.g. `.bashrc`,
`.zshrc` etc.). This is intended for permanently enabling experimental
features in your environment.
1. Creating a `.env` file in the same directory as your root Taskfile that
contains the relevant environment variables. e.g.
```shell
TASK_X_FEATURE=1
```
The dotenv reader will …
> Support for experiment env vars

- CHANGELOG.md
- args/args.go
- args/args_test.go
- cmd/task/task.go
- docs/docs/experiments/experiments.md
- internal/experiments/experiments.go
- task.go
- task_test.go
- taskfile/call.go
- testdata/force/Taskfile.yml
Note: This depends on #1214 
Implements a draft version of the [gentle force experiment](https://github.com/go-task/task/issues/1200). Based on the experiments branch and [PR](https://github.com/go-task/task/pull/1214).
This works by adding a new field to the `taskfile.Call` struct called `Direct` which is only set when a task is called directly from the CLI. Another new field is added to the `Executor` called `ForceAll`. Depending on whether or not the experiment is enabled, we set the Executor's `Force` and `ForceAll` fields and then we will skip fingerprinting if the task is direct and the executor is set to force, OR if the executor is set to force all.
> feat: implement gentle force experiment draft

- errors/errors_task.go
- task.go
This PR fixes a couple of minor output related "problems" with the new `prompt` feature:
- Removes duplicated double quotes. We don't need to add quotes when using `%q`:
- Removes the newline after the prompt is requested. This makes the output a bit tidier:
Before:
After:
> Small prompt fixes

- internal/experiments/experiments.go
Fixes #1244 
Simply squashes all errors related to reading the dotenv. If its not there, we don't care. We just don't load anything from it.
> fix: ignore all errors when reading dotenv for experiments

- docs/docs/installation.md
I just added `task` to the `tea` package manager, see https://tea.xyz/+taskfile.dev/ and https://github.com/teaxyz/pantry/pull/2323
This MR adds the related installation documentation.
According to the update statement, `tea` is automated at this: https://github.com/teaxyz/pantry#after-your-contribution
Greetings
> docs: Add tea installation

- task_test.go
- taskfile/read/taskfile.go
- testdata/include_with_vars_multi_level/Taskfile.yml
- testdata/include_with_vars_multi_level/bar/Taskfile.yml
- testdata/include_with_vars_multi_level/foo/Taskfile.yml
- testdata/include_with_vars_multi_level/lib/Taskfile.yml
Previously, included vars would be set to nil upon being included by another taskfile. They are now propagated up during the include process.
This is especially problematic for users who want to use library-like taskfiles in a monorepo.
```
├── common
│   └── docker.yml
├── service-a
│   └── Taskfile.yml 
├── service-b
│   └── Taskfile.yml
└── Taskfile.yaml
```
You can imagine that the contents of `service-a/Taskfile.yml` resemble
```yaml
version: '3'
includes:
docker:
taskfile: ../common/docker.yml
vars:
DOCKER_IMAGE: service-a
```
Fixes: 
- https://github.com/go-task/task/issues/778
- https://github.com/go-task/task/issues/996
> fix: propagate include vars in multi-level includes

- CHANGELOG.md
- task.go
- task_test.go
- testdata/error_code/Taskfile.yml
Fixes #1266
This bug is happening because when we run a command, we are always wrapping the `interp.exitStatus` error and returning a `TaskRunError`:
https://github.com/go-task/task/blob/7e7a016df393373ec9322b6fbadc1cbc3db61366/task.go#L232-L243
This works fine at the top-level (for direct calls) because we can simply unwrap the error in Task's main function: 
https://github.com/go-task/task/blob/7e7a016df393373ec9322b6fbadc1cbc3db61366/cmd/task/task.go#L84-L87
However, when we run a command _indirectly_ via another task, we are wrapping the `TaskRunError` in another `TaskRunError`. This problem is recursive and means that we can't effectively unwrap the error to get the exit code out.
The solution to this is simply to check if the command is being called directly and if not, we return …
> fix: exit codes for indirect tasks

- taskfile/merge.go
I accidentally had an empty `deps` row in a nested config, like so:
```
tasks:
task-name:
deps:
- dep-task-name 
- # commented-out-task-name  , but at wrong place!
```
This caused a panic like this:
```
> task --version
Task version: 3.27.1
> task
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1028c0fb0]
goroutine 1 [running]:
github.com/go-task/task/v3/taskfile.Merge.func1({0x140001dc350, 0xe}, 0x140001fb0e0)
github.com/go-task/task/v3/taskfile/merge.go:44 +0xd0
github.com/go-task/task/v3/internal/orderedmap.(*OrderedMap[...]).Range(0x102a1c5e0, 0x140001337a8)
github.com/go-task/task/v3/internal/orderedmap/orderedmap.go:114 +0xa4
github.com/go-task/task/v3/taskfile.Merge(0x140001347e0, 0x14000200fc0, …
```
> fix: add nil guards in dependency merge

- docs/docs/usage.md
I was banging my head on this for quite some time, reading the docs and trying to get loops working. Eventually I started looking through the issue queue to see if there were bugs reported on this functionality. After reading through the issue queue, I learned that this feature is new, and therefore not available on the version of task that is installed using homebrew. Since using this feature on older versions of Task reports no errors or warnings, I think this little documentation change would be helpful for others.
> docs: add required version for supporting loops

- .github/workflows/test.yml
- CHANGELOG.md
- go.mod
[Go 1.21 was recently released](https://golang.org/blog/go1.21). This PR bumps the minimum required version to 1.20 inline with our promise of compatibility with the latest 2 versions of Go.
> feat: bump minimum go version to 1.20

- CHANGELOG.md
- internal/filepathext/filepathext.go
- setup.go
- task.go
- task_test.go
- taskfile/included_taskfile.go
- testdata/user_working_dir_with_includes/Taskfile.yml
- testdata/user_working_dir_with_includes/included/Taskfile.yml
Closes #1046
Closes #1205
Closes #1250
Closes #1293
Closes #1274
Closes #1312
Also reported at [this Discord thread](https://discord.com/channels/974121106208354339/1141402520229511208)
> fix: make sure USER_WORKING_DIR works corrently with includes

- CHANGELOG.md
- cmd/task/task.go
Closes https://github.com/go-task/task/issues/1305
Closes https://github.com/go-task/task/pull/1307
> fix: `--status` flag should not have side-effects

- CHANGELOG.md
- errors/errors_taskfile.go
- setup.go
- taskfile/read/node.go
- taskfile/read/node_base.go
- taskfile/read/node_file.go
- taskfile/read/taskfile.go
This work is closely linked to #1152. In summary, I have pulled out the refactor changes that are a precursor to the remote Taskfile work. This is the stuff that continuously needs to be rebased as it conflicts with other areas of the codebase. Once this is merged, it should be significantly easier to work on #1152 without it conflicting with other changes.
This work includes the new `Node` interface which abstracts the logic for reading a Taskfile into various implementations (Just regular file reading for now). None of the changes here impact any of the outstanding decisions to be made in #1152 and can safely be merged without any changes to behaviour/functionality.
> feat: node refactor

- CHANGELOG.md
- args/args.go
- args/args_test.go
- cmd/task/task.go
- docs/docs/experiments/remote_taskfiles.md
- errors/errors.go
- errors/errors_taskfile.go
- internal/experiments/experiments.go
- internal/logger/logger.go
- setup.go
- task.go
- task_test.go
- taskfile/included_taskfile.go
- taskfile/read/cache.go
- taskfile/read/node.go
- taskfile/read/node_base.go
- taskfile/read/node_file.go
- taskfile/read/node_http.go
- taskfile/read/taskfile.go
#770 is now the most requested feature in Task by quite some margin and there have been frequent requests/questions around it in recent weeks. Previous requests have been rejected based on complexity, but I believe that the way this draft is implemented might actually reduce the Task reader complexity as it abstracts the logic for dealing with files away from the recursive reader. 
This PR is intended to open a dialogue about how this feature might look if it is added to Task. Please note that this is _first draft_ and is open to significant changes or rejection entirely.
The first commit only contains changes to the underlying code to allow it to be more extensible via a new `Node` interface. This interface allows for multiple implementations of the Taskfile reader. This change also …
> feat: remote taskfiles (HTTP)

- go.mod
- go.sum
- internal/templater/funcs.go
Enough of pinning by commit hash. Finally tagged a release. 🙂 
https://github.com/go-task/slim-sprig/issues/14
> chore(deps): upgrade slim-sprig to v3.0.0

- CHANGELOG.md
- setup.go
- taskfile/read/node_file.go
- taskfile/read/taskfile.go
Fixes #1331 
- fix: `e.Dir` not being set to the correct directory
- fix: only create a cache if the node is remote
The issue was that `e.Dir` wasn't being set to the root taskfile location after reading the taskfiles, so it was set to the working directory instead.
This fix causes some issues with the cache directory for the remote taskfiles experiment, but fixing the core functionality is the priority.
> fix special variables

- CHANGELOG.md
- docs/docs/api_reference.md
- errors/errors.go
- errors/errors_taskfile.go
- taskfile/read/taskfile.go
Fixes #1341
Checks if the Taskfile and the schema version are `nil` after decoding and either of them are, will return a `TaskfileVersionNotDefinedError` (107).
Also updates the error codes section of the API references doc.
> feat: error handling for undefined schema version

- watch.go
- watch_test.go
Limits ignore files to exact 4 directories used to be ignored before ".git/.hg/node_modules/.task"
Usecase: setting up monitoring for the files that matches ignored directory, but not location inside of it. So for example, we I want (actual case I run into) to monitor "yaml" templates and test them on change, I can't use `.github` directory as it ignored by default because it matches `.git`.
> fix: exclude other "ignored" files.

- CHANGELOG.md
- docs/docs/experiments/remote_taskfiles.md
- internal/logger/logger.go
- setup.go
- task.go
- task_test.go
- taskfile/read/taskfile.go
This allows the `--yes` flag to work for all prompts (including the ones in the remote Taskfiles experiment) and reduces some duplicated prompt code.
> feat: unify prompts

- task.go
- task_test.go
- testdata/list_desc_interpolation/Taskfile.yml
When a task description has uses templates, they are not properly compiled when listing the tasks.
This was reported back in https://github.com/go-task/task/issues/276 and then fixed in https://github.com/go-task/task/pull/283
I think then there was a regression in f22389a8
I don't have much experience in go and in this project context, I've tried my best to find the real issue.
> fix: templates on task descriptions

- CHANGELOG.md
- internal/goext/meta.go
- task.go
- testdata/platforms/Taskfile.yml
> fix(platforms): do not run dynamic vars for other platforms

- CHANGELOG.md
- docs/static/schema.json
Fixes #1385 
It seems that the `for_call` schema doesn't contain many of the elements from a normal `cmd_call` though I'm not sure which parts are valid for the `for_call` other than the `silent` element so didn't copy those across
> Add silent to for_call schema

- CHANGELOG.md
- cmd/task/task.go
- docs/docs/experiments/remote_taskfiles.md
- errors/errors.go
- errors/errors_taskfile.go
- setup.go
- task.go
- taskfile/read/taskfile.go
As per discussion in https://github.com/go-task/task/pull/1152#issuecomment-1705085513, this PR changes the Remote Taskfiles experiment to prefer remote files over locally cached ones.
Previously, if a user used the `--download` flag to cache a file, this file would be automatically preferred over the remote copy. The only way to get a newer version of that file was to delete the cached version entirely.
The new behaviour always prefers the remote copy and will always attempt to fetch and use it _unless_ the user specifies the `--offline` flag (in which case Task will search for a cached version).
In addition to this, if the network times out, when trying to fetch a remote copy, Task will now search for a cached version and use that instead.
---
My question now is... Do we need …
> feat: prefer remote taskfiles over cached ones

- docs/docs/api_reference.md
- docs/i18n/es-ES/docusaurus-plugin-content-docs/current/api_reference.md
- docs/i18n/fr-FR/docusaurus-plugin-content-docs/current/api_reference.md
- docs/i18n/ja-JP/docusaurus-plugin-content-docs/current/api_reference.md
- docs/i18n/pt-BR/docusaurus-plugin-content-docs/current/api_reference.md
- docs/i18n/ru-RU/docusaurus-plugin-content-docs/current/api_reference.md
- docs/i18n/tr-TR/docusaurus-plugin-content-docs/current/api_reference.md
- docs/i18n/zh-Hans/docusaurus-plugin-content-docs/current/api_reference.md
Fixed typo `downlaoded` in the docs
> chore(docs): fix downlaoded typo

- CHANGELOG.md
- help.go
- internal/editors/output.go
Fixes #1430 
Only point of note - I decided that when `aliases` is empty, it should marshal to `[]` instead of `null` or being omitted. Welcome to opinions on this, but an empty array makes the most sense to me.
> feat: add aliases to --json output

- CHANGELOG.md
- args/args.go
- args/args_test.go
- cmd/task/task.go
- docs/docs/experiments/any_variables.md
- docs/static/schema.json
- internal/compiler/env.go
- internal/compiler/v2/compiler_v2.go
- internal/compiler/v3/compiler_v3.go
- internal/experiments/experiments.go
- internal/output/output_test.go
- internal/templater/templater.go
- task.go
- task_test.go
- taskfile/for.go
- taskfile/read/dotenv.go
- taskfile/taskfile_test.go
- taskfile/var.go
- testdata/vars/any/Taskfile.yml
- variables.go
This is the first iteration of the "Any Variables" experiment that allows users to use any type in their Taskfile variables. In this PR:
- Adds the `TASK_X_ANY_VARIABLES` experiment flag
- Renames `Var.Static` -> `Var.Value`
- Changes `Var.Value` to an `any` type
- Unmarshal into `any` type instead of just strings when the experiment flag is enabled.
- Updated schema to support objects and arrays in vars
- Added some experiment docs
- `for` supports arrays when looping over a variable
- Added an error message when trying to use `sh` with the experiment enabled
- Added new syntax for dynamic variables
There are no tests in this PR as its an experiment. However, I have added a Taskfile in `testdata/vars/any` which can be used to try out the functionality:
`go run ./cmd/task --dir …
> Support any variables

- docs/docs/experiments/any_variables.md
- testdata/vars/any/Taskfile.yml
- variables.go
Adds support for looping over a map-type variable using the `for` syntax. Since Go maps are unordered, the order of the loop will be random.
This also fixes a bug where specifying a map variable when looping over a variable would give an invalid error about using `sh` with the Any Variables experiment.
> feat: support looping over map variables

- docs/docs/deprecations/template.md
- docs/docs/deprecations/version_2_schema.md
- docs/docs/experiments/any_variables.md
- docs/docs/experiments/experiments.md
- docs/docs/experiments/gentle_force.md
- docs/docs/experiments/remote_taskfiles.md
- docs/docs/experiments/template.md
- docs/docs/styleguide.md
- Removed an old section from the styleguide that stated that `taskfile.yml` files (with a lowercase 't') are not supported. This is no longer true since #1221 was merged.
- Updated the format of the experiments & deprecations docs to make the warnings much clearer. The production warning from the main experiments page has now been copied into each individual experiment page too so that users see it if they navigate directly to an experiment.
Before
After
> docs: improved experimental docs formatting

- args/args.go
- args/args_test.go
- cmd/task/task.go
- task.go
- task_test.go
- taskfile/ast/call.go
The API for `taskfile/ast.Call.Direct` isn't great when using Task as a Go package. Creating a task as if it were being called from the CLI means you have to write something like this:
```go
call := ast.Call{Task: "default", Direct: true}
```
I can't think of many situations where you would want to set `Direct: false` from an API as this mainly intended for internal use when parsing a `ast.Cmd` or `ast.Dep`. Additionally, it's easy to forget to add `Direct: true` and omitting it is probably not the behaviour you want.
If we invert the property name from `Direct` to `Indirect`, the default value becomes `false` and so when calling a task with the API you would simply need to do:
```go
call := ast.Call{Task: "default"}
```
> feat: invert call.Direct

- go.mod
- internal/templater/funcs.go
Adds the spew function to templater which lets you print the details of a variable. This is really useful for debugging now that we have multiple variable types.
> feat: add spew function to templater

- docs/docs/usage.md
- internal/templater/funcs.go
- testdata/vars/any/Taskfile.yml
Adds a very basic `merge` template function that will iterate over maps A and B and put all their elements into a new map M. Map B will overwrite map A if a key conflicts. The new map M is returned leaving the original maps unchanged.
Not sure where functions like this should be documented as we seem to have 3 sources for template functions:
- Go templating itself
- Slim Sprig
- Task
> feat: added basic merge template function

- docs/docs/usage.md
- internal/templater/funcs.go
- testdata/vars/any/Taskfile.yml
As per https://github.com/go-task/task/pull/1438#discussion_r1448956303
> feat: merge template func should support variadic list of maps

- completion/zsh/_task
Allow Taskfiles starting with lowercase characters in zsh completion since it is supported since v3.27.0 - 2023-06-29
> fix(completions): support lowercase filename for Taskfile

- docs/static/schema.json
- errors/errors.go
- errors/errors_taskfile.go
- setup.go
- task_test.go
- taskfile/ast/taskfile.go
- taskfile/reader.go
- feat: version checks
- refactor: consistent naming for errors
- feat: update schema to accept semver strings
Task's current version checking is a bit out of date and unused. It's a lot of work for us to maintain a list of features and which schema versions they work in, but it's quite trivial to let a user specify a minimum version of task as their schema version and then error if the version of the binary is lower.
This PR extends the existing `TaskfileVersionNotDefined` error (exit code 107) and renames it to the more generic `TaskfileVersionCheckError`. This error is then used whenever we come across a problem with schema/binary versions. In this PR, this happens in 3 places:
1. When reading a Taskfile, if the `version` key is not provided:
```
task: Missing schema version in …
```
> feat: version checks

- docs/docs/api_reference.md
- internal/compiler/compiler.go
- setup.go
> feat: add ROOT_TASKFILE special variable

- cmd/task/task.go
- help.go
Fixes #1509
- fix: setup logger if nil when listing task names
- refactor: bubble errors from ListTaskNames
@andreynering An alternative approach to fixing this would be the following diff. It would simplify the code as we no longer have to conditionally load the taskfile/logger in `ListTaskNames()`. This obviously comes with a slight performance cost.
```diff
diff --git a/cmd/task/task.go b/cmd/task/task.go
index f3144703..17f9884c 100644
--- a/cmd/task/task.go
+++ b/cmd/task/task.go
@@ -264,15 +264,15 @@ func run() error {
return err
}
+       if err := e.Setup(); err != nil {
+               return err
+       }
+
if (listOptions.ShouldListTasks()) && flags.silent {
e.ListTaskNames(flags.listAll)
return nil
}
-       if err := e.Setup(); err != nil {
-               return err
- …
```
> fix: panic when using --list and --silent

- docs/docs/api_reference.md
https://github.com/go-task/task/commit/6ed30f1addf85dcf015e3586008e3f9bdf59041d ensures that variable declaration order is respected, but this wasn't documented as far as I could tell. This PR adds a note about it to the API reference.
> docs: specify that variable declaration order is respected

- docs/docs/styleguide.md
some suggestions for improving the style guide
> Style guide: improved spelling and wording

- args/args.go
- args/args_test.go
- cmd/task/task.go
- docs/docs/usage.md
- errors/errors_task.go
- internal/compiler/compiler.go
- internal/summary/summary.go
- internal/summary/summary_test.go
- requires.go
- status.go
- task.go
- task_test.go
- taskfile/ast/task.go
- taskfile/ast/tasks.go
- testdata/wildcards/Taskfile.yml
- variables.go
- watch.go
Fixes #836
This PR is a proposal for a design that would allow basic wildcard matching for task names. At the moment, if users want to make a generic task that performs a common set of operations on many different services or directories (etc) they must either:
1. Pass a variable into Task using environment variables
2. Use `.CLI_ARGS` and the `--` operator
Both of these methods can be clunky to type into a CLI and are not very intuitive. `make` has the option to do wildcard matching (using `%`). This PR is a proposal to do the equivalent in Task.
When a Taskfile has a task with a name that contains a wildcard (`*`) and the user calls `task` with a task name that "matches" a wildcard task, that task will be run. Matches will occur by replacing any instances of `*` with the `(.*)` regex …
> feat: wildcard matching for task names

- docs/docs/api_reference.md
- docs/docs/faq.md
- docs/docs/installation.md
- docs/docs/usage.md
- docs/docusaurus.config.ts
- setup.go
- taskfile/node.go
- taskfile/node_file.go
- taskfile/node_http.go
- taskfile/node_stdin.go
- taskfile/reader.go
- taskfile/taskfile.go
Closes #655
Adds a new `StdinNode` that implements the `Node` interface. This is a special-case Node that only gets created if Task detects bytes in stdin when starting. I've refactored the way we create "root" nodes (i.e. nodes without parents) in order to do this. I think the result is a bit nicer and lays the groundwork for root remote nodes too.
I also had to resolve an issue in the reader where an included file's `BaseDir` was only being set for `FileNode`. I have added a `BaseDir()` method to the `Node` interface and this will now be added by any node that returns a non-empty string when calling this method.
Lastly, I have updated the docs with a section on reading from stdin. This also includes a commit that adds some missing syntax highlighters to our docs site and standardises …
> feat: read Taskfiles from stdin

- cmd/task/task.go
- help.go
Fixes #1514
This change removes an optimisation in favour of reducing complexity. There is nothing particularly time consuming that we are skipping in `e.Setup()` and this code has been the source of several recent bugs including #1514 and #1509.
> fix: list tasks

- cmd/task/task.go
- internal/flags/flags.go
- task.go
Simple refactor to move flags into their own package.
Just an idea that I was poking around at. It means that all the code to do with flags is isolated and cleans up the `cmd/task.go` file a bit. Definitely subjective though, so it's fine if you're not a fan.
> refactor: move flags into their own package

- docs/docs/api_reference.md
- internal/compiler/compiler.go
- taskfile/ast/task.go
- taskfile/reader.go
Fixes #1522
Fixes the `TASKFILE_DIR` variable and adds a new `TASKFILE` variable.
> feat: taskfile special variable

- setup.go
- task_test.go
- taskfile/node.go
- testdata/special_vars/Taskfile.yml
- testdata/special_vars/included/Taskfile.yml
Fixes #1529
This issue was caused by a change in #1483 that moved where the Taskfile directory was calculated. This resulted in Task behaving weirdly in situations where a Taskfile is located in a parent directory to the user's current working directory. This was partly fixed in #1522. However, the core issue still remained.
This PR fixes any remaining related issues by moving the directory calculation entirely into the `NewRootNode()` function and then fetching the calculated dir from the resulting node in `e.Setup()`. The node creation has also been moved earlier in the executor setup in order to fix another unreported bug where the temporary `.task` directory was created in the wrong place.
> fix: taskfile directory

- internal/compiler/compiler.go
- internal/deepcopy/deepcopy.go
- internal/output/group.go
- internal/output/interleaved.go
- internal/output/output.go
- internal/output/output_test.go
- internal/output/prefixed.go
- internal/templater/templater.go
- task.go
- taskfile/dotenv.go
- taskfile/reader.go
- testdata/vars/any2/Taskfile.yml
- variables.go
Fixes #1477
Fixes #1511
This PR overhauls the way templating works in Task. Instead of having methods on `templater.Template`, we now have package-level functions instead. This allows us to use generics (as generic methods aren't possible right now) which vastly simplifies the calling API. This is especially useful for the "Any Variables" experiment since many types of variable may need to support templating.
For example, we now have the ability to support collection-type variables (slices/maps) and these might contain strings in which we want to use templates. See example below:
```yml
version: '3'
vars:
IMAGE_TAG: 'latest'
tasks:
default:
vars:
works: '{{.IMAGE_TAG}}'
does:
map:
not:
work: '{{.IMAGE_TAG}}'
cmds:
- 'echo {{.works}}'
- 'echo {{.does.not.work}}'
```
Running the above …
> feat: parse templates in collection-type variables

- internal/compiler/compiler.go
- task_test.go
- testdata/include_with_vars_multi_level/lib/Taskfile.yml
Followup to #1256
Fixes #1503
Quite a small/simple change that allows #1503 to work as expected. I would personally have expected the changes in #1256 to have required the use of `default` to work correctly. This feels more consistent with how was pass variables around between tasks, but I might be misunderstanding. Variable propagation is complicated in Task 😆 
Is this a breaking change?
> fix: variables passed to included taskfile

- cmd/task/task.go
- internal/flags/flags.go
- setup.go
- task_test.go
- taskfile/ast/include.go
- taskfile/node.go
- taskfile/node_base.go
- taskfile/node_file.go
- taskfile/node_http.go
- taskfile/node_stdin.go
- taskfile/reader.go
- taskfile/taskfile.go
- website/static/Taskfile.yml
- website/versioned_docs/version-latest/experiments/remote_taskfiles.md
Fixes #1531
This PR enables the ability to pass a remote Taskfile URI to the `--taskfile` flag. This means that your root Taskfile no longer needs to exist locally.
When specifying the `--taskfile` flag, Task usually assumes that the execution directory is the directory that the root Taskfile resides in. Since this isn't possible with a remote Taskfile, the execution directory will default to the current working directory instead when the Task command is executed.
However, I have also added the ability to change this default directory using the existing `--dir` flag. This now means that you are able to specify BOTH `--taskfile` and `--dir` flags simultaneously - Something that was not previously allowed. The following semantics are now applied:
- If `--taskfile` is specified without …
> feat: enable root remote taskfiles

- internal/logger/logger.go
- website/docs/api_reference.mdx
Adds support for multiple ANSI attributes and 8-bit colours when specifying `TASK_COLOR_X` variables. Pairs nicely with the functionality in #1572.
You can specify multiple codes by separating them with a semicolon. For example: `31;1` will make the text bold and red. You can specify 8-bit colours by using the sequence `38;2;R;G;B` for foreground colours and `48;2;R;G;B` for background colours where `R`, `G` and `B` should be replaced with values between 0 and 255.
For convenience, you can also specify 8-bit foreground colours using a shorthand, comma-separated syntax: `R,G,B`. For example, `255,0,0` is equivalent to `38;2;255;0;0`.
> feat: support 8-bit color

- CHANGELOG.md
- internal/execext/exec.go
> fix: fix bug for files with special chars `&()`

- internal/experiments/experiments.go
- taskfile/ast/var.go
- website/blog/2023-09-02-introducing-experiments.mdx
- website/blog/2024-04-09-variables.mdx
- website/docs/experiments/gentle_force.mdx
- website/docs/experiments/map_variables.mdx
- website/docs/experiments/remote_taskfiles.mdx
- website/docs/experiments/template.mdx
- website/docs/installation.mdx
- website/docs/taskfile_versions.mdx
- website/docs/usage.mdx
- website/docusaurus.config.ts
This PR is a proposal to merge support for the "Any Variables" experiment into main, but without support for maps. The experiment has been open for a while now and as far as I can tell, there have been no issues with the support for basic variable types (`bool`, `int`, `float`, `arrays`). The only contentious issues have been around maps and the breaking changes involved.
This PR removes the `TASK_X_ANY_VARIABLES` experimental flag so that all functionality from the experiment is generally available with the exception of map variables which are now locked behind the new `TASK_X_MAP_VARIABLES` flag. 
All of the docs have been updated to reflect these changes and I've also added a short (draft) blog post too!
Thing to do if proposal accepted:
> feat: enable any variables without maps

- website/docusaurus.config.ts
We've been having a hard time dealing with translations recently. It simply stopped working recently and I'm quite frustrated honestly, because trying to fix it has distracted me from other relevant work.
It's useless to show all the languages on the menu while they are not working (the text is a copy of the English version), so I'm disabling them for now.
> chore(website): disable translations for now

- CHANGELOG.md
- internal/templater/funcs.go
- website/docs/usage.mdx
- website/versioned_docs/version-latest/usage.mdx
> feat: add alias `q` for template function `shellQuote`

- completion/zsh/_task
taskfile specified with ~ are not expanding properly so -f check is failing.
taskfile with "some path/that has paces/Taskfile.yml" does not work because it is being double quoted
and if you want to preserve behavior for parent dir searches, we could also add this snip:
```
+    local curdir
cmd=(task)
taskfile=${(Qv)opt_args[(i)-t|--taskfile]}
@@ -19,12 +20,17 @@ function __task_list() {
enabled=1
cmd+=(--taskfile "$taskfile")
else
+      curdir=`pwd`
+      while [ "$enabled" -eq 0 -a `pwd` != '/' ]; do
for taskfile in {T,t}askfile{,.dist}.{yaml,yml}; do
if [[ -f "$taskfile" ]]; then
enabled=1
break
fi
done
+        cd ..
```
> Support tilde home directory auto completion and spaces in directories

- errors/errors.go
- errors/errors_taskfile.go
- task_test.go
- taskfile/ast/graph.go
- taskfile/ast/include.go
- taskfile/reader.go
- testdata/includes/Taskfile.yml
- testdata/includes/module1/Taskfile.yml
- testdata/includes/module2/Taskfile.yml
- testdata/includes/module3/Taskfile.yml
- testdata/includes/module4/Taskfile.yml
Fixes #1606
Allows someone to create multiple includes to/from the same Taskfiles. This was restricted when we moved to the DAG reader implementation. The DAG library we use does not support adding multiple edges between nodes. However, the problem is easily solved by changing the edge data from `*ast.Include` to `[]*ast.Include`. This also allows us to easily calculate the weight (number of connections) of any edge by calculating the length of the slice.
I've also undone the changes to some of the tests that used to use multiple includes that were changed when the DAG reader was implemented.
> feat: add support for multiple includes on a graph edge

- .golangci.yml
- go.mod
- go.sum
- internal/compiler/compiler.go
- internal/templater/funcs.go
- internal/templater/templater.go
- testdata/vars/any2/Taskfile.yml
- variables.go
- website/docs/experiments/map_variables.mdx
This PR adds the ability to resolve references to other variables using Golang's templating syntax.
For example:
```yaml
version: '3'
tasks:
ref-resolver:
vars:
MAP:
map: {"name":"Alice","age":30,"children":[{"name":"Bob","age":5},{"name":"Charlie","age":3},{"name":"Diane","age":1}]}
MAP_REF:
ref: .MAP # <-- now requires "dot" syntax
cmds:
- task: print-var
vars:
VAR:
ref: (index .MAP_REF.children 0).name # <-- use brackets and functions normally
print-var:
cmds:
- echo "{{.VAR}}" # <-- echos "Bob"
```
Since this functionality is not exposed by the standard library, it depends on a [fork](https://github.com/go-task/template) of the `text/template` package and the changes in [this PR](https://github.com/go-task/template/pull/1).
> feat: ability to resolve refs using templating syntax

- cmd/task/task.go
- internal/experiments/experiments.go
- internal/flags/flags.go
- internal/logger/logger.go
Prints a warning when `TASK_X_ANY_VARIABLES` is set informing the user that it is no longer required. It will pointer users who require map variables to the new `TASX_X_MAP_VARIABLES` experiment instead.
> feat: warn about move from any variables to map variables

- task_test.go
- taskfile/node_http.go
- taskfile/reader.go
- testdata/includes_interpolation/include_with_env_variable/Taskfile.yml
- website/docs/experiments/remote_taskfiles.mdx
I've added the support of env variable in include remote. All env variable presents in the URL (${ENV}) will be replaced.
Related to : https://github.com/go-task/task/discussions/1420#discussioncomment-7752658
> feat(remote): replace env variable in include remote URL

- taskfile/reader.go
I think there is a bug introduced during the [PR introducing DAG](https://github.com/go-task/task/pull/1563).
The prompt is still displayed when it's empty.
cf :
> fix(remote): do not display prompt if it's empty

- taskfile/node.go
Fixes #1593
Reading Taskfiles from stdin now required `-t -` instead of implicitly reading from stdin if it detects content. This is to fix a regression which stops users from using stdin to pipe data to their actual tasks.
> feat: stdin required -t -

- website/static/schema.json
This fixes some typos in the [schema file](https://taskfile.dev/schema.json) that I found when updating at https://github.com/SchemaStore/schemastore/issues/3328.
> fix: Fix schema typos

- internal/env/env.go
- task_test.go
- testdata/env/Taskfile.yml
Hey @pd93,
I've tried a solution to fix : 
- https://github.com/go-task/task/issues/1640
It's because since the any vars, some vars are detected as int or float and do not get added to the env map.
So we can let them passthrough and convert them with `%v`
I've also added a test to convert this case
> fix: handle int and float env variable by converting them to string

- website/docs/contributing.mdx
- website/versioned_docs/version-latest/contributing.mdx
Add correct references for the links to experiments and experiment workflows in the Contributing page.
[Link to section](https://taskfile.dev/contributing/#before-you-start)
Before:
After:
> fix(docs): add references to experiments links

- task_test.go
- taskfile/ast/tasks.go
- testdata/included_taskfile_var_merging/Taskfile.yaml
- testdata/included_taskfile_var_merging/bar/Taskfile.yaml
- testdata/included_taskfile_var_merging/foo/Taskfile.yaml
Fixes #1643 
Small bug with included variable merging when multiple included files use the same variable. This is fixed temporarily by deep copying the variable values. Long term fix for this will be removing merging all together (I'm actively working on this).
> fix: included variable merging

- internal/compiler/compiler.go
Fixes #1616
I've gone with `TASK_EXE` instead of `TASK_EXECUTABLE` as suggested simply because its a bit shorter. Thoughts welcome.
> feat: task executable variable

- cmd/task/task.go
- errors/error_taskfile_decode.go
- errors/errors.go
- errors/themes/task.xml
- go.mod
- go.sum
- task_test.go
- taskfile/ast/cmd.go
- taskfile/ast/dep.go
- taskfile/ast/for.go
- taskfile/ast/glob.go
- taskfile/ast/include.go
- taskfile/ast/output.go
- taskfile/ast/platforms.go
- taskfile/ast/platforms_test.go
- taskfile/ast/precondition.go
- taskfile/ast/task.go
- taskfile/ast/taskfile.go
- taskfile/ast/tasks.go
- taskfile/ast/var.go
- taskfile/reader.go
This PR greatly improves the error reporting of YAML issues by surfacing the real parsing errors from `yaml.v3` and providing a syntax highlighted snippet of the error and its location. It also provides a clickable link to the error location (if using a supported editor terminal like VSCode).
Syntax highlighting is provided through [chroma](https://github.com/alecthomas/chroma) and I have added a custom theme that looks good for terminals that only support 8 colours.
Some examples:
> better yaml parsing

- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/upload-source-documents.yml
Node 16 is deprecated so I've bump checkout / setup-go and setup-arduino to the lastest version
> chore: update actions version because node 16 is deprecated

- website/docs/deprecations/template_functions.mdx
- website/docs/reference/_category_.yml
- website/docs/reference/cli.mdx
- website/docs/reference/environment.mdx
- website/docs/reference/schema.mdx
- website/docs/reference/templating.mdx
- website/docs/usage.mdx
Fixes #1614
Adds a reference for templating variables and functions to the docs. Since this makes the reference extremely long, I have also split it into 4 pages:
I have also added the deprecated functions to the deprecations doc so that they are not forgotten about in the future.
> docs: template reference

- internal/compiler/compiler.go
- internal/templater/templater.go
- task_test.go
- taskfile/ast/var.go
- testdata/var_references/Taskfile.yml
- testdata/vars/any2/Taskfile.yml
- website/docs/experiments/map_variables.mdx
- website/docs/reference/templating.mdx
- website/docs/usage.mdx
- website/static/schema.json
This does the following:
- References can now be used in the base code (no experiments needed)
- If the "Map Variables" experiment (proposal 1) is enabled, references can be accessed by prefixing with `#`
- This is similar to how dynamic variables are prefixed with a `$`.
- Adds deprecation warnings for template functions to the deprecations documentation
- Template functions can now be used in references (`ref`).
- Fixes #1645
- Removes `json` and `yaml` keys from map variable experiment
- The same functionality can now be achieved by using `ref: fromJson {...}`
- Docs:
- Removed `ref`, `yaml` and `json` docs from Map Variables 2 experiment doc
- Added section on ref prefix (`#`) in Map Variables 1 experiment
- Added a "References" sections to the "Usage" documentation
- Added a section …
> feat: variable references

- website/docs/taskfile_versions.mdx
Pairs nicely with the changes in #1663.
This updates the desperately out-of-date Taskfile Versions doc and removes most of the old information about version 1 & 2. I don't think this information is often used and we don't really have any docs explaining how schema versions _currently_ work in v3. I think this is a good place for them to go.
As always, thoughts/comments/suggestions welcome
> docs: taskfile versions

- website/docs/installation.mdx
Improve the installation docs : 
- Example with a specific version for the installation script
- Adding pacstall method (community owned)
I've checked the repo is still maintained : 
Closes #1352
> docs: improve install script

- .goreleaser.yml
Tested result:
```
root@visionfive2-1:~/task# uname -a
Linux visionfive2-1 5.15.0-starfive #1 SMP Sun Jun 11 07:48:39 UTC 2023 riscv64 GNU/Linux
root@visionfive2-1:~/task# go test
PASS
ok      github.com/go-task/task/v3      25.144s
root@visionfive2-1:~/task# env GOBIN=/bin go install ./cmd/task
/bin/task --version
Task version: (devel) ()
root@visionfive2-1:~/task# task
task: [lint] golangci-lint run
task: [install] go install -v ./cmd/task
task: [test] go test github.com/go-task/task/v3 github.com/go-task/task/v3/args github.com/go-task/task/v3/cmd/release github.com/go-task/task/v3/cmd/sleepit github.com/go-task/task/v3/cmd/task github.com/go-task/task/v3/errors github.com/go-task/task/v3/internal/compiler github.com/go-task/task/v3/internal/deepcopy …
```
> chore: release riscv64 binary on Linux

- hash.go
- internal/hash/hash.go
- internal/slicesext/slicesext.go
- task_test.go
- taskfile/ast/task.go
- taskfile/ast/tasks.go
- testdata/run_once_shared_deps/Taskfile.yml
- testdata/run_once_shared_deps/library/Taskfile.yml
- testdata/run_once_shared_deps/service-a/Taskfile.yml
- testdata/run_once_shared_deps/service-a/src/imasource.go
- testdata/run_once_shared_deps/service-b/Taskfile.yml
- testdata/run_once_shared_deps/service-b/src/imasource.go
- variables.go
Fixes #852
This PR changes the hash we use when a task is marked as `run:once`. Previously we used the full name of the task. This is fine most of the time, but when a task in an included Taskfile is included multiple times, the name will contain a namespace that is different for each task. Using the example given in #852, the hashes produced are:
```
service-a:build
service-b:build
service-b:library:build #  <-- this...
service-a:library:build #  <-- is different to this
```
As a result `library:build` is run twice, even though it is marked as `run: once`.
In this PR, we are creating a hash that is a combination of the file location and the name of the task _without a namespace_. This means that the hash is unique for each task, but will be the same when a task is included in different …
> fix: run once in shared dependencies

- help.go
- setup.go
- status.go
- task.go
- task_test.go
- variables.go
- website/docs/experiments/remote_taskfiles.mdx
- website/docs/reference/environment.mdx
This PR allow to have a global temp directory when using remote taskfile.
Considering a setup with multiple different projects, all using the same remote taskfile. if /  when the remote taskfile changes, we need to approve the prompt for all projects.
At the beginning, I thought changing the TASK_X_TEMP_DIR to `~/.task`, but I've seen that it's suffixed with the dir so I won't work.
The fingerprint dir should stay scoped
This PR changes the behavior only for remote. If the path is absolute or start with `~` then we do not suffix it.
For the implementation, I've chosen to create a struct and store the two paths in it. We could also in the future add an env variable like `TASK_X_REMOTE_DIR`. If you think it can be a nice addition, I can implement it in this PR 
Any feedback on this feature …
> feat(remote): global tempDir when the path is absolute

- taskfile/cache.go
- taskfile/node.go
- taskfile/node_file.go
- taskfile/node_http.go
- taskfile/node_stdin.go
I've introduce a new concept in node, the `filename`. This will allow us to store remote checksums/cached files with a more user-friendly filename
Linked to : 
- https://github.com/go-task/task/issues/1317
> feat(remote): prefix checksums/cached files with the filename

- cmd/task/task.go
- website/versioned_docs/version-latest/api_reference.mdx
> Add verbose/silent variables

- cmd/task/task.go
- internal/flags/flags.go
- taskfile/cache.go
- website/docs/experiments/remote_taskfiles.mdx
I've added a command to clear the cache for remote files.
I've made the choice to disallow using download and clear-cache at the same time because clear-cache should be used as standalone.
We could allow using both flags at the same time, but we need to define the bahavior : 
- Clear cache override download (so we clear the cache but not download)
- Download override clear cache (so we download but not clear cache)
> feat(remote): add a command to clear the cache

- internal/version/version.go
We went a bit too far when refactoring this. Some people build Task theirself and provide the version with ldflags. But in our implementation we override the version.
fixes #1709 
I used this command to check : 
`go build -o "task" -ldflags "-s -w -X github.com/go-task/task/v3/internal/version.version=3.38.0"  ./cmd/task ` like they do in Homebrew (https://github.com/Homebrew/homebrew-core/blob/e71417b07f53e9ea7c79974dd6f6c2297d9a9a1c/Formula/g/go-task.rb#L23-L32)
> fix: --version when a version is provided with -ldflags

- website/docs/reference/templating.mdx
Related to : 
- https://github.com/go-task/task/pull/1669
It was done on `versioned_docs` which was overriden by docs and lost in the process
> docs: add CLI_SILENT and CLI_VERBOSE in the docs

- .github/workflows/lint.yml
A small proposal: check in the CI if files under versioned_docs has been modified.
We had the issue twice (https://github.com/go-task/task/pull/1669 && https://github.com/go-task/task/pull/1673) so I think doing this check in the CI can be useful
EDIT : this one too : https://github.com/go-task/task/pull/1702
Here is what it looks like : 
I've put it under `lint` because I did not want to create another workflow file
> ci: add new job to check if versioned_docs has been modified

- internal/env/env.go
- internal/experiments/experiments.go
- task_test.go
- testdata/env/Taskfile.yml
- website/docs/experiments/env_precedence.mdx
Linked to : 
- https://github.com/go-task/task/issues/1038
I am totally open to rework this, including add new template function (as discussed in discord)
> feat: experiment taskfile envs take precedence over os envs

- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- go.mod
- hash.go
- help.go
- internal/deepcopy/deepcopy.go
- internal/logger/logger.go
- internal/slicesext/slicesext.go
- requires.go
- setup.go
- signals.go
- signals_test.go
- task.go
- task_test.go
- taskfile/ast/tasks.go
- testdata/list_desc_interpolation/Taskfile.yml
- variables.go
[Go 1.23 has been released](https://go.dev/blog/go1.23), so it's time to bump our minimum version again.
Previously, we supported 1.21 and 1.22. This PR bumps the minimum version to 1.22 and drops support for 1.21. Our tests/linter will now run against 1.22 and 1.23.
Bumping the minimum version allows us to use some of the [features introduced in 1.22](https://go.dev/doc/go1.22). There are a number of changes are relevant to this project, including:
- [Ranging over integers directly](https://go.dev/ref/spec#For_range)
- No more `for i := 0; i < len(s); i++` loops. We can now do `for i := range len(s)`.
- [Changes to how loop variables are set](https://go.dev/blog/loopvar-preview)
- No need to do weird things like `idx := i` in closures anymore. It just works.
- I've updated a test to …
> Update minimum go version

- CHANGELOG.md
- internal/execext/exec.go
- task.go
- task_test.go
- testdata/exit_code/Taskfile.yml
- variables.go
- website/docs/reference/templating.mdx
- website/docs/usage.mdx
Original issue: #1484.
Based on the work started by @dorimon-1 on #1673.
> feat(defer): expose `EXIT_CODE` special variable to `defer:`

- internal/compiler/compiler.go
- testdata/special_vars/Taskfile.yml
- testdata/special_vars/included/Taskfile.yml
- website/docs/reference/templating.mdx
Adds `ALIAS` to special vars that represents the alias that was used when invoking the task, otherwise will be the task name.
```bash
> go run ./cmd/task --dir testdata/special_vars echo-task-alias
task: [print-task-alias] echo "echo-task-alias"
echo-task-alias
> go run ./cmd/task --dir testdata/special_vars print-task-alias
task: [print-task-alias] echo "print-task-alias"
print-task-alias
```
> feat: add ALIAS special var

- website/docs/usage.mdx
`.MYVAR` was a typo, it should be `.FOO` instead
> docs: fix variable name

- cmd/task/task.go
- completion.go
- internal/flags/flags.go
- website/docs/deprecations/completion_scripts.mdx
- website/docs/installation.mdx
Fixes #293
A draft PR based off [this comment](https://github.com/go-task/task/issues/293#issuecomment-1542105162). 
It's a pretty simple implementation. We have a new internal package called `completion`. This will embed any files in the `internal/completion/templates/*` directory and when the `--completion <shell>` flag is given, it will read the template with the corresponding template name, insert any template values and return the string which will then be output to stdout.
I've added a `task.tpl.example` file to illustrate how you would add a completions script. I'm not super proficient with completion scripts (I have a bit of experience with ZSH), so maybe if we're happy with this approach, we can merge with no templates and slowly migrate the old scripts to this new concept.
I …
> feat: completions command

- completion/fish/task.fish
Fixes #1781 
Before : 
After : 
@davinkevin It would be amazing if you could test it before we release this. I test it locally with the docker container it sounds fine
> fix(completion): display aliases in fish completion

- taskfile/ast/for.go
- variables.go
I noticed that the unit tests for the matrix implementation are flaky. This is because the order of the input maps is not preserved. e.g.
```yaml
loop-matrix:
cmds:
- for:
matrix:
OS: ["windows", "linux", "darwin"]
ARCH: ["amd64", "arm64"]
cmd: echo "{{.ITEM.OS}}/{{.ITEM.ARCH}}"
```
can result in both:
```txt
windows/amd64
windows/arm64
linux/amd64
linux/arm64
darwin/amd64
darwin/arm64
```
and:
```txt
windows/amd64
linux/amd64
darwin/amd64
windows/arm64
linux/arm64
darwin/arm64
```
I have made it so that the output is always the former example.
> fix: matrix loops should be deterministic

- task_test.go
- taskfile/ast/tasks.go
- testdata/includes_flatten/Taskfile.with_default.yml
- testdata/includes_flatten/Taskfile.yml
Fixes #1777 
I've also added a test to cover this case
> fix: include flatten with a default task

- internal/experiments/experiments.go
Initially reported in 
- https://github.com/go-task/task/issues/1805
I took a look and discover when we call `task --help` double usage is printed
I've tracked it down to https://github.com/go-task/task/pull/1478
Flagset parse automatically --help to display usage.
A simple fix is to override `usage` func
Now :
> fix: double help is printed when `--help` is provided

- task.go
- task_test.go
- testdata/exit_code/Taskfile.yml
Fixes https://github.com/go-task/task/issues/1803
@andreynering I am not sure about this part.
If it does not look good, feel free to re-do it from scratch
> fix: interpolate vars in defer

- task.go
- task_test.go
- testdata/exit_code/Taskfile.yml
Fixes #1803 
We need to evaluate sh vars in defer cmds
> fix: interpolate dynamic vars in defer

- .goreleaser.yml
refs https://github.com/goreleaser/goreleaser/issues/5142
docs should be better, but its not a good idea to use `tag` in the snapshot version template
this should fix the issue you're having
> fix: snapshot builds and wrong winget version

- variables.go
Solves https://github.com/go-task/task/issues/1822
> Fix: Cannot use splitArgs and splitLines in for-loops

- internal/version/version.go
PR #1711 fixed variable `version` being overridden, this PR ensures that the same does not happen to `sum`.
EDIT: This patch is being shipped in the `go-task` package for Arch Linux.
> fix: checksum override when passed via ldflags

- taskfile/reader.go
Fixes #1832 
I've choose to re-use the mutex on the graph.
Maybe you have a better solution @pd93
> fix(remote): wait for prompt in the reader

- task_test.go
- taskfile/dotenv.go
- testdata/dotenv/parse_error/.env-with-error
- testdata/dotenv/parse_error/Taskfile.yml
> fix: Print dotenv file path when there is an error reading file

- task_test.go
The executor output for parallel task (and dep) execution can come out one character at a time, so even though the tests use `SyncWriter`, the writer's lock doesn't prevent interleaving.
Using `group` output forces the task output to be buffered and kept together before being printed.
Fixes https://github.com/go-task/task/issues/1819.
> fix: Flaky TestForDeps tests

- internal/compiler/compiler.go
fixes #1232 
What caused the bug? In dotenv, we use the templater (to allow the use of variables in dotenv's path), and if the user includes a special variable in their template, there was a template error because special variables were not defined.
Special variables that are not linked to a task and/or a call are always available.
> fix: special variables are defined with dotenv at task level

- website/docs/usage.mdx
It's rather often than not you need to use a default value for a variable, and then adjust it to your needs. There's no documentation can be found on how to achieve that so this PR should address this issue
> docs: add an example of a `default` value usage in vars

- internal/compiler/compiler.go
- taskfile/ast/var.go
- variables.go
Fixes #1903
This PR changes the `Sh` property of a `Var` to a pointer so that we are able to distinguish between a value that is not set (`nil`) and a value that is empty (`&""`). We then use this to return early if we detect an empty dynamic variable. This will always resolve to another empty string.
This fixes cases where a dynamic variable contains a template that resolves to an empty string.
> fix: bug where non-nil, empty dynamic variables are returned as an empty interface

- CHANGELOG.md
- cmd/sleepit/sleepit.go
- internal/compiler/compiler.go
- task_test.go
- testdata/env/Taskfile.yml
- testdata/exit_immediately/Taskfile.yml
- testdata/summary/Taskfile.yml
- testdata/summary/task-with-summary.txt
- website/docs/changelog.mdx
- website/docs/usage.mdx
- website/versioned_docs/version-latest/changelog.mdx
- website/versioned_docs/version-latest/usage.mdx
This PR corrects spelling mistakes in the CHANGELOG, Go comments, and testdata filenames.
See https://www.noslangues-ourlanguages.gc.ca/en/writing-tips-plus/dependant-dependent
> fix: typos in docs, changelog, testdata, comments

- go.mod
- go.sum
- taskfile/node.go
- taskfile/node_git.go
Switch from https://github.com/whilp/git-urls to https://github.com/chainguard-dev/git-urls. See https://github.com/whilp/git-urls/issues/24 and https://github.com/whilp/git-urls/issues/28. Many scanning tools complain about that.
> chore(deps): switch to mainted fork of `git-urls`

- website/static/schema.json
I've been getting errors from my editor that using `platforms` as a sibling of `for` under `cmds` is not supported, when it is in fact supported and respected by task
I believe this was missed on #980
- This change simply adds a small fix to the json schema to denote that
`platforms` is allowed with `for`
🖼️ Before
🖼️ After
> fix(json-schema): add missing `platforms` property to cmds `for`

- .golangci.yml
- task_test.go
- testdata/env/Taskfile.yml
- find commonly misspelled english words
The past participle for "override" is "overridden", both in American and in British English: 
https://www.oxfordlearnersdictionaries.com/definition/english/override?q=override
> chore: add linter misspell

- .golangci.yml
- cmd/release/main.go
- internal/execext/exec.go
- internal/flags/flags.go
- precondition.go
This PR enables [`depguard`](https://golangci-lint.run/usage/linters/#depguard) linter to allow using only `github.com/go-task/task/v3/errors` package for consistency across the project. The `errors` package from stdlib is forbidden.
> chore: allow using only github.com/go-task/task/v3/errors package

- internal/compiler/compiler.go
This PR fixes #1920  to correctly log dynamic variables by dereferencing `Sh`
> fix: dynamic variable output in verbose mode

- website/docs/changelog.mdx
- website/docs/reference/schema.mdx
- website/static/schema.json
- Fix the `defer_call` JSON schema to include the `vars` mapping.
- Update the schema reference documentation to cover `defer: {task: ..., vars: {...}}`.
> docs: Document defer task options

- task.go
- task_test.go
- testdata/requires/Taskfile.yml
Fixes : 
- https://github.com/go-task/task/issues/1950
Two thing here : 
- The template should be evaluated (in `CompiledTask`) only after verifying the required variables.
- `skipFingerprint` should not bypass the required variable checks.
> fix: evaluate requires before compiled task

- internal/compiler/compiler.go
- task_test.go
- testdata/special_vars/Taskfile.yml
- website/docs/reference/templating.mdx
fixes 
- https://github.com/go-task/task/issues/1959
I think it's a good addition
> feat: add TASK_DIR special variable

- internal/templater/templater.go
- task_test.go
- taskfile/ast/include.go
- taskfile/ast/tasks.go
- taskfile/ast/var.go
Another attempt to fix ordered map race conditions. This is built on top of the new ordered map implementation in #1797 and replaces #1608.
> fix: omap race

- internal/output/prefixed.go
When using the `prefixed` output format, I occasionally get a `fatal error: concurrent map writes` error due to concurrent modifications to the `seen` map used by `Prefixed`.
This change adds a mutex protecting the Prefixed struct.
> fix: concurrent mutations to prefixWriter

- task_test.go
- testdata/cmds_vars/Taskfile.yml
- testdata/cmds_vars/source.txt
- variables.go
- website/docs/usage.mdx
Hello, this is my attempt to implement #1735.
> feat: Make CHECKSUM and TIMESTAMP vars available in cmds commands

- website/docs/reference/environment.mdx
- website/docs/reference/package.mdx
- website/docs/reference/schema.mdx
- website/docs/reference/templating.mdx
Closes #1958
Adds a new doc that states that the package API exists, but is not stable. I have some ideas about how to make the package API more user friendly and will extend this document when we have things that we think are a bit more stable.
> docs: package api doc

- website/docs/installation.mdx
Standardises the layout for all installation methods, adds labels and links to sources where possible. Also reorders the list with the official methods at the top and community owned ones at the bottom.
Also closes the longstanding #935.
> docs: updated installation guides

- website/docs/usage.mdx
Because if you don't use spaces, it looks like this:
> docs: fix some examples to use spaces instead of tabs

- signals.go
Renaming: The constant interruptSignalsCount has been renamed to maxInterruptSignals to better reflect its purpose, which is to define the maximum number of interrupt signals that can be handled.
Loop Fix: The loop condition has been corrected to iterate from 0 to maxInterruptSignals, ensuring that the loop runs the expected number of times.
> refactor: signal handling to improve clarity and correctness

- cmd/task/task.go
- init.go
- init_test.go
- task_test.go
Fixes #2009.
When using the `--init` flag to create a new Taskfile, it currently prints the whole contents of the file to the terminal, which is unnecessarily verbose (and honestly seems to be unintentional).
This PR fixes it by only printing the filename by default and taking the `--silent` and `--verbose` flags into account to control the behavior:
```
$ task --init
Taskfile.yml created in the current directory
```
```
$ task --init --silent
```
```
$ task --init --verbose
version: '3'
vars:
GREETING: Hello, World!
tasks:
default:
cmds:
- echo "{{.GREETING}}"
silent: true
Taskfile.yml created in the current directory
```
Please note that I purposefully did not update the description of the `--silent` and `--verbose` flags so please let me know if you want me to and what should I change …
> feat: make Taskfile initialization less verbose by default

- task_test.go
- taskfile/node_http.go
After this [commit](https://github.com/go-task/task/commit/c77c8a419b0c4b6905882c61bc663df5aaef6289), building internal graph can raise error because HTTPNode's Location value can be changed while building graph. (See line 65 (`node.URL = url`))
So if taskfile imports remote file with multiple depth (e.g. A --> remote B --> remote C) without filename, it raises
```
source vertex https://{PATH_TO_REMOTE}/Taskfile.yaml: vertex not found
```
So fixing `HTTPNode.Location` not to be changed over time.
(I couldn't find any related issues, so please let me know if there's issue or I have to create it)
> fix: `HTTPNode.Location` when building graph

- requires.go
- task.go
- task_test.go
- testdata/requires/Taskfile.yml
- Fixes #2032 
I've split the check into two methods:
- One for the `requires`  which should be evaluated before the task being compilated (this allows for a well-formed message when using this variable in a template, see: #1950 / #1970 )
- One for the allowed values, which works with dynamic variables.
> fix: requires allowed values works with dynamic var

- task_test.go
- testdata/cmds_vars/Taskfile.yml
- testdata/status_vars/Taskfile.yml
- variables.go
fixes #2029 
@pd93 Before, both `{{.TIMESTAMP}}` and `{{.CHECKSUM}}` were available in `status`, but according to our documentation, only one should be available depending on the chosen method.
cf : https://taskfile.dev/usage/#using-programmatic-checks-to-indicate-a-task-is-up-to-date
> fix(checker): use only one checker at the same time to improve perf

- Taskfile.yml
@andreynering Maybe I'm missing something. This has been here since long before I came across Task. Is there a reason that `task test` works the way it does? In most of my projects, I just have `task test` setup to run `go test ./...`, but in our own Taskfile it will install the binary first. This isn't usually what I want to do during development.
Just opening this as a suggestion. Thanks :)
> feat: stop task test installing task

- cmd/task/task.go
- internal/env/env.go
- internal/experiments/errors.go
- internal/experiments/experiment.go
- internal/experiments/experiment_test.go
- internal/experiments/experiments.go
- internal/flags/flags.go
- internal/logger/logger.go
- setup.go
- task_test.go
- taskfile/ast/var.go
- taskfile/node.go
Closes #1979
Refactors the experiments package slightly so that experiments only need to be specified in one place now. Also moved the print functions to the logger to avoid importing anything in the experiments package. This stops circular imports.
This way of doing things allows us to easily iterate over all experiments which means I was able to easily add a function that validates all experiments. If an experiment is inactive (has no enabled values) and a user tries to specify a value, a warning will now be output.
Finally, I've consolidated how we read any Task-namespaced environment variables into the new `env.GetTaskVar` function that will always prefix `TASK_` to any variables read. The logger now only reads these variables once instead of every time a call to print is made.
> feat: experiments logging improvements

- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .golangci.yml
- go.mod
- internal/version/version.go
Bumps the minimum Go version to v1.23. This allows us to start using 1.23 features in the next version of Task! Tests will now run on 1.23 and 1.24.
> chore: bump minimum version to 1.23

- setup.go
- taskfile/node.go
- taskfile/node_file.go
- taskfile/node_http.go
- taskfile/reader.go
- taskfile/taskfile.go
Our package API should not rely on our internal `logger` package. Logging is a CLI-specific responsibility and users that want to use Task as a package may want to implement their own logging. As such, this PR removes the logger from the `taskfile` package entirely.
Normally this would mean we lose the ability to insert debug logs into our code. However, we can pass a generic function into the `Reader` which will process logs instead. This allows all of Task's current logging to remain in place while a 3rd party user can either omit the logging function when creating their reader (and discard the logs) or implement their own custom logging.
I have also done the same thing for the prompt function so that package API users can implement their own prompt functionality.
Finally, the reader …
> feat: remove logger from taskfile package

- internal/experiments/errors.go
- internal/experiments/experiment.go
- internal/experiments/experiment_test.go
- internal/experiments/experiments.go
- internal/slicesext/slicesext.go
- internal/slicesext/slicesext_test.go
- task_test.go
- taskfile/ast/var.go
- testdata/requires/.task-experiments.yml
- website/docs/experiments/experiments.mdx
- website/static/schema-taskrc.json
- #1978 
I like this idea ! 
This file should override the environment variable.
> feat: add a new .taskrc.yml to enable experiments

- website/docs/community.mdx
- website/docs/contributing.mdx
- website/docs/deprecations/deprecations.mdx
- website/docs/experiments/experiments.mdx
- website/docs/getting_started.mdx
- website/docs/integrations.mdx
- website/docs/intro.mdx
- website/docs/reference/_category_.yml
- website/docs/styleguide.mdx
- website/docs/taskfile_versions.mdx
- website/docs/usage.mdx
As mentioned in https://github.com/go-task/task/pull/2011#pullrequestreview-2573000290, the getting started docs could do with a bit of an overhaul. The usage page has slowly grown and become a bit daunting to a new user. It also doesn't mention `--init` in any capacity.
This PR solves both of these by adding a new Getting Started page to the website. This page is written more as a tutorial than a reference which is friendlier to new users. It instructs the user how to create a new Taskfile using `--init`, how to call it and how to write a basic build task.
> docs: getting started

- task_test.go
- taskfile/ast/matrix.go
- testdata/for/cmds/Taskfile.yml
- testdata/for/deps/Taskfile.yml
- variables.go
Fixes #2065
Based on-top of #2068, this allows `ref` to be used in a `MatrixRow`. For example:
```yml
version: '3'
vars:
OS_VAR: ["windows", "linux", "darwin"]
ARCH_VAR: ["amd64", "arm64"]
tasks:
default:
silent: true
cmds:
- for:
matrix:
OS:
ref: OS_VAR
ARCH:
ref: ARCH_VAR
cmd: echo "{{.ITEM.OS}}/{{.ITEM.ARCH}}"
```
```
windows/amd64
windows/arm64
linux/amd64
linux/arm64
darwin/amd64
darwin/arm64
```
> feat: allow variable references in a matrix

- .golangci.yml
- task_test.go
- taskfile/snippet.go
The [`mirror`](https://golangci-lint.run/usage/linters/#mirror) linter detects places where allocations can be avoided.
> chore: add linter mirror

- task_test.go
- taskfile/ast/vars.go
- testdata/include_with_vars_inside_include/Taskfile.yml
- testdata/include_with_vars_inside_include/include/Taskfile.include.yml
A regression was introduced in this [PR](https://github.com/go-task/task/pull/1797).
When a dynamic variable is provided, even if it is not used, all other variables become unavailable in the templating system.
> fix: include with dynamic vars

- compiler.go
- setup.go
- taskfile/dotenv.go
Fixes #2106
Also related to:
- #1810
The fundamental issue is that some special variables are not available when evaluating variables outside of a task. This causes the error seen in #2106 and has actually been an issue for a while. However, it was only surfaced in 3.42 because of the refactor in #2084 which moved a call to `GetTaskfileVariables` without moving the corresponding `if len(tf.Dotenv) == 0 {...}` check.
This PR fixes both of these issues:
- Special variables that we are not able to calculate now evaluate to an empty string instead of `nil`. This avoids type errors like the one seen in #2106.
- The validation check for dotenv files has been moved to before the call to `GetTaskfileVariables` again.
> fix: special variable type errors in vars with no task context

- cmd/task/task.go
- executor.go
- help.go
- internal/flags/flags.go
- setup.go
- task.go
- task_test.go
- taskfile/reader.go
- taskfile/snippet.go
- watch_test.go
This PR migrates the `Executor` to use the functional options pattern. This follows other similar changes to `taskfile.Reader` and `taskfile.Snippet`. This allows package API users to easily construct an `Executor` with sensible defaults and only supply a list of things they want to override.
Our internal CLI implementation has a special functional option in `internal/flags` called `WithFlags` which will gather all the CLI flags and pass them in as functional options.
> refactor: executor functional options

- init.go
- taskfile/templates/default.yml
Moves the default Taskfile used when calling `--init` to an embed rather than storing it in the code.
> refactor: embed the default Taskfile instead of defining it in code

- completion/fish/task.fish
This PR fixes the following error on fish 4.0.1.
```
~/.config/fish/completions/task.fish (line 5): The expanded command was empty.
$GO_TASK_PROGNAME --list-all 2>&1 | read -lz rawOutput
^~~~~~~~~~~~~~~~^
```
In the commit, I specified `function --inherit-variable GO_TASK_PROGNAME`.
I consider this is safe as the option is introduced 10 years ago <https://github.com/fish-shell/fish-shell/commit/cfc06203>.
I tested fish 3.0.2 (2020) and 3.7.1 (2025) and 4.0.1 (2025) and all of them works fine.
> fix(fish): fish completion error due to variable shadowing

- task.go
- task_test.go
- website/docs/usage.mdx
Fixes #2072 
As discussed in #2072 and https://github.com/go-task/task/pull/1489#discussion_r1499811332, this PR allows calls to match multiple tasks when using wildcards. For example, given the following Taskfile:
```yaml
version: 3
tasks:
start:*:*:
vars:
SERVICE: "{{index .MATCH 0}}"
REPLICAS: "{{index .MATCH 1}}"
cmds:
- echo "Starting {{.SERVICE}} with {{.REPLICAS}} replicas"
start:*:
vars:
SERVICE: "{{index .MATCH 0}}"
cmds:
- echo "Starting {{.SERVICE}}" 
```
Currently, if you run `task start:foo:1`, you will get an error:
```
task: Found multiple tasks (start:*:*, start:*) that match "start:foo:1"
```
However, after this change you will see
```
Starting foo with 1 replicas
```
and if you run `task start:foo`, you will get
```
Starting foo
```
Worth noting that the order is …
> feat: allow wildcards to match multiple tasks

- compiler.go
Fixes #1911
A small bug was introduced in #1904 where undefined/null variables were resolved as an empty string instead on `nil`.
> fix: bug where undefined/null variables resolve to "" instead of nil

- website/docs/installation.mdx
Found out that the install script parameters seem to be order specific so worth documenting it
e.g.
Will ignore the `-b ~/temp` and install `v3.30.0` into `./bin`
```shell
sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d v3.30.0 -b ~/temp
```
> docs: specify that install command parameters are order specific

- .github/workflows/lint.yml
- .golangci.yml
[golangci-lint](https://golangci-lint.run/) released v2 recently, I have simply run their [migration tool](https://golangci-lint.run/product/migration-guide/) on our existing config for now.
> feat: migrate to golangci-lint v2

- executor.go
- task_test.go
- website/docs/reference/templating.mdx
- website/docs/usage.mdx
> fix: `.USER_WORKING_DIR` should contain the value of `--dir` if given

- completion/fish/task.fish
In the current implementation, fish completion suggests local tasks regardless of `-g` or `--global` options.
This PR fixes the problem by adding a feature to detect these options and then suggesting global tasks if likely.
I hope this PR can be merged although I do not implement the feature for bash and zsh.
I am not familiar with them...
> feat(completion): let fish complete global tasks if -g or --global is passed

- go.mod
- go.sum
- internal/execext/exec.go
- internal/fingerprint/glob.go
- setup.go
- taskfile/node_file.go
- taskfile/node_git.go
- taskfile/node_http.go
- taskfile/node_stdin.go
- variables.go
Fixes #2073 
Removes `zglob` as a dependency and instead relies on mvdan's `expand.Fields` with globbing turned on for `sources` globs.
We also use `expand.Fields` in multiple other places to resolve things like `~` and environment variables. However, most of the time, we don't also want brace expansion or globbing, so I have separated this into two functions. One wraps `expand.Literal` which returns a single string with just the variables resolved, and the other wraps `expand.Fields` with braces and globbing enabled.
> fix: sources brace expansion

- setup.go
- taskfile/reader.go
- website/docs/reference/package.mdx
This PR contains some new package API docs that I have been working on and a very small refactor to the `taskfile.Reader` type that removes the `Node` field in favor of it being passed in as an argument to the `Reader.Read` method.
I have further sections for this doc in progress (Such as `Executing tasks`), but want to wait until I have submitted a few other changes before they are published.
> docs: package api docs

- args/args.go
- cmd/task/task.go
CLI_ARGS shoud be a string and not an array
Introduced in #2166
> fix: CLI_ARGS is a string and not an array

- executor_test.go
- setup.go
- testdata/fuzzy/Taskfile.yml
- testdata/fuzzy/testdata/TestFuzzyModel-fuzzy-err-run.golden
- testdata/fuzzy/testdata/TestFuzzyModel-fuzzy.golden
- testdata/fuzzy/testdata/TestFuzzyModel-not-fuzzy.golden
Linked to #2192
Tested locally :
> fix: fuzzy model was not instanciated

- internal/execext/exec.go
Fixes #2208
in #2075 (released in v3.43.1), we changed the way that expanding paths works so that it directly uses mvdan's `expand.Literal`. However, this has resulted in us double-escaping paths because of our internal `escape` function. Switching to `p.Document` and removing the `escape` function seems to fix the problem.
I have double-checked that issues like #1551, #1590 and #2073 have not regressed.
> fix: double escaped paths

- internal/templater/funcs.go
- website/docs/reference/templating.mdx
Fixes #2217
Adds 4 YAML templating functions to match the existing JSON ones from slim-sprig:
- `fromYaml`
- `mustFromYaml`
- `toYaml`
- `mustToYaml`
Note there is no `toPrettyYaml` as YAML encoding has newlines/indentation by default and no `toRawYaml`.
> feat: add yaml templating functions

- args/args.go
- cmd/task/task.go
- website/docs/reference/templating.mdx
Fixes #2139 
Fixes #2138
Adds a new `CLI_ARGS_LIST` global variable which contains the pre-dash arguments in an array.
> feat: `CLI_ARGS_LIST` global variable

- website/docs/usage.mdx
The docs does not mention that `method` can be used at root level.
Fixes #975
> docs: mention that method key is allowed at root level

- formatter_test.go
- help.go
- internal/editors/output.go
- task_test.go
- testdata/json_list_format/Taskfile.yml
- testdata/json_list_format/testdata/TestJsonListFormat.golden
- website/docs/reference/cli.mdx
Hi, nice to meet you, and thanks for developing the task tool!
I'm implementing [the tui client](https://github.com/aleksandersh/task-tui) for the task. I have decided that the best way to integrate a user interface is to use the JSON output feature (`task --list --json`).
All works fine except [the labels](https://taskfile.dev/usage/#overriding-task-name). If some tasks have the label field, the JSON output will contain it instead of the real name. Since I can't request the execution by the task label, the client is stuck here.
https://github.com/go-task/task/blob/da4ce5b0a58c328f83c5813806ab5e6265e93fdc/taskfile/ast/task.go#L53
I found the same problem in the vscode plugin (https://github.com/go-task/vscode-task/issues/167) since it is integrated with the task in the same way.
I assume …
> feat: add task name to the json output

- errors/errors.go
- errors/errors_taskfile.go
- executor_test.go
- taskfile/ast/include.go
- taskfile/node.go
- taskfile/node_base.go
- taskfile/reader.go
- testdata/includes_checksum/correct/Taskfile.yml
- testdata/includes_checksum/correct/testdata/TestIncludeChecksum-correct.golden
- testdata/includes_checksum/correct_remote/Taskfile.yml
- testdata/includes_checksum/included.yml
- testdata/includes_checksum/incorrect/Taskfile.yml
- testdata/includes_checksum/incorrect/testdata/TestIncludeChecksum-incorrect-err-setup.golden
- website/docs/experiments/remote_taskfiles.mdx
- website/docs/reference/schema.mdx
- website/static/next-schema.json
Closes #2222
Adds the ability to pin remote _and_ local Taskfiles using a checksum. Extract from the included changes to the remote Taskfile docs:
> Alternatively, if you expect the contents of your remote files to be a constant value, you can pin the checksum of the included file instead:
> 
> ```yaml
> version: '3'
> 
> includes:
>   included:
>     taskfile: https://taskfile.dev
>     checksum: c153e97e0b3a998a7ed2e61064c6ddaddd0de0c525feefd6bba8569827d8efe9
> ```
> 
> This will disable the automatic checksum prompts discussed above. However, if the checksums do not match, Task will exit immediately with an error. When setting this up for the first time, you may not know the correct value of the checksum. There are a couple of ways you can obtain this:
> 
> 1. Add the include normally …
> feat: checksum pinning

- go.sum
- internal/fsnotifyext/fsnotify_dedup.go
- watch.go
Hello,
This is a small refactor of the `Deduper` component, here's a list of the introduced changes :
* Move the `Deduper` timers map to goroutine, to avoid mutex usage as it's read from / written to from a single goroutine.
* `Deduper.GetChan` now returns a receive only channel, as only the internal `fsnotify.Watcher` instance should be allowed to send events to it.
* Use `fsnotify.Event.Has` to check against Chmod operations (as per recommended by the `fsnotify.Event.Op` godoc).
* In `Executor.watchTasks` - remove check against Chmod operations, it's already handled in the `Deduper.GetChan` goroutine.
* Add a little bit of godoc on the `Deduper.GetChan` method to explain that.
* Run a `go mod tidy`.
Following the contributing guidelines, I will squash the commits upon merging (if it …
> refactor(fsnotifyext): remove unnecessary mutex usage from Deduper

- watch.go
- watch_test.go
- Fixes #2202
- Fixes #2199
Some testing is highly appreciated! Let me know if this fixes the issues you're having or not.
/cc @davidkuridza @noahfraiture @pot-code @SheGe
> fix(watcher): fix some v3.43.x regressions

- install-task.sh
- website/static/install.sh
The install-task.sh script was converting "armv7*" to "arm" in function `uname_arch()`, checking that "arm" value in `uname_arch_check()`, and then finally using a case condition based on "armv7" in function `get_binaries()`. So of course the download would fail.
[GO Arch only includes linux/arm](https://pkg.go.dev/internal/platform#pkg-variables) variant.
Solution is to fix the `get_binaries()` function.
fixes #1516 
Download tested on PI aarch64, script modified with hardcoded arch as "arm7l". Expected version of task was downloaded.
> Fix install script for armv5/6/7.

- internal/templater/funcs.go
- website/docs/reference/templating.mdx
> fix: remove extra breaking randInt function

- internal/execext/exec.go
Fixes #2321 which was caused by the changes in #2216. Looks like the `escape` is still needed for globbing. I have (again) checked that all previous issues in this chain are still working as expected. Hopefully this is resolved once and for all now.
> fix: spaces in path

- .github/workflows/release-nightly.yml
- .goreleaser.yml
Now that we have GoReleaser Pro, it might be a good idea to publish nightly pre-releases.
Some other projects have it. I took inspiration from GoReleaser itself.
I wasn’t able to test it yet because I don’t have the KEY.
> chore: publish nightly

- .github/workflows/release-nightly.yml
- .github/workflows/release.yml
- .goreleaser-nightly.yml
- .goreleaser.yml
The nightly release was published as draft
Also the title was incorrect.
I've made the choice use another yaml config to not impact our "real" release workflow
> fix: publish nightly draft and title

- .goreleaser.yml
I’ve created a team, and we’re using the Open Source free tier, which should be sufficient for our needs!
I’ve added the `CLOUDSMITH_TOKEN` as a secret variable in the GitHub Actions workflow.
I haven’t been able to test it yet, but according to Cloudsmith, we can use `any-version` since our binary is statically compiled.
I haven’t updated the documentation yet because the website is being rewritten. Also, I wanted to test how it works first before making any updates.
> build: publish deb and rpm to cloudsmith

- website/.vitepress/config.ts
- website/.vitepress/theme/custom.css
- website/Taskfile.yml
- website/package.json
- website/src/public/_redirects
Remove the padding in the team page
Also one redirect was wrong, a / was missing
> docs: remove padding in team page and fix redirect

- .github/workflows/release-nightly.yml
- .github/workflows/release.yml
- .goreleaser-nightly.yml
- .goreleaser.yml
It fixes multiple issues : 
- Missing `CLOUDSMITH_TOKEN`
- remove some commas to be yaml compliant
The cloudsmiths integration with deb packages does not work and needed to be fixed before merging
> fix: goreleaser with cloudsmith and npm

- website/.vitepress/config.ts
- website/src/docs/reference/environment.md
I noticed this was accidentally removed during the migration.
> fix: readd environment reference

- taskrc/node.go
- taskrc/taskrc.go
- taskrc/taskrc_test.go
- website/src/docs/reference/config.md
Fixes #2390 by changing the name of the `$XDG_CONFIG_HOME/task` config to `taskrc.yml` or `taskrc.yaml` (without the preceding `.`).
@vmaerten @panchoh w.r.t discussion in #2390, I'm not against `config.yml`, but after a bit of thinking I actually feel like ripgrep might have got this right. The naming consistency is valuable IMO. It lets you know that you're editing the same kind of file with the same schema and I think `$XDG_CONFIG_HOME/task/taskrc.yml` is the way to go. Happy to be outvoted on this though!
Once agreed and merged, I will open a PR to the schemastore repo.
---
Also the related discussion on Discord around the inclusion of the `$HOME` directory when running from a directory that does not have `$HOME` as a parent.
See updated docs for a full description.
> feat: change XDG taskrc naming

- Taskfile.yml
As discussed in Discord, 
Use [gotestsum](https://github.com/gotestyourself/gotestsum) which is just a UI wrapper around go test
It's way better to see which tests failed. It also support Github actions output
> chore: use gotestsum for test

- completion/zsh/_task
Fixes https://github.com/go-task/task/issues/950
Our binary already knows how to locate the Taskfile, let it handle that, and just capture the return code in the autocomplete function.
> fix: autocomplete from subfolder works as expected in zsh shell

- errors/errors_taskfile.go
- setup.go
Before this patch, a generic `file does not exist` is being shown, which is not useful enough.
We used to have a user-friendlier message in the past, but it probably was lost in the recent refactors.
Before:
```bash
$ task
file does not exist
```
After:
```bash
$ task
task: No Taskfile found at "/Users/andrey/Developer/repo" (or any of the parent directories). Run `task --init` to create a new Taskfile.
```
> fix: fix message shown when a taskfile was not found
